### PR TITLE
fix cuda build on appveyor, remove old unsupported config on macOS

### PR DESCRIPTION
**Pull request by cenit**
I noticed that CUDA was not really built on Windows with the latest revision, this should just make sure that CUDA is really installed and tested.
I also removed the gcc@5 build on macOS, because of the error explained in here: https://github.com/AlexeyAB/darknet/pull/2476
Unfortunately any gcc newer than that was already unsupported, and it seems that on newer OpenCV@3 builds also that gcc went broken. `brew` just went crazy removing all flags for default packages (https://github.com/Homebrew/homebrew-core/issues/31510) but this became in a real mess for me in many works, because it is now impossible to ask for packages with special options or linked with a different stdlib. In this case, the real problem is in fact rooted to a discrepancy between `libc++` and `libstdc++` (clang vs gcc).
Instead of fighting with an old compiler and an old toolchain, I think it's easier to just remove it and completely declare it unsupported.

### CODE REVIEW

**Comment by cenit** [comment]
by the way, on windows I also took the opportunity to update Cuda to 10.1, just to test how Darknet is behaving in this case.
Later this coming week I will also open a PR which will be fully related to using Darknet as a library, improving target exports from CMake and setting the ground for the promised `vcpkg` recipe which will build and install everything extremely easily ;)

**Comment by cenit** [comment]
I also took the opportunity to refresh the build scripts based on feedback and problems from your users. They should be less error-prone and give some more exhaustive messages whenever needed. As always, please let me know any comment you may have.
(btw sorry for the problem with the mjpeg-stream, we never review those modifications and I can't even recall which problem they gave me at the beginning, so sorry for the trouble)

**Comment by tinohager** [comment]
@cenit Can you add the artifacts in the build script? https://github.com/AlexeyAB/darknet/issues/2346

**Comment by cenit** [comment]
sure, why not? I added them :)
Please let me know if you want something different from what I did

**Comment by tinohager** [comment]
@cenit For me it is important that both libaries are available in the artifacts. The libaries should by build with opencv support. (yolo_cpp_dll and yolo_cpp_dll_no_gpu). Also I would need the right dependencies for example OpcenCV 3.4.0 and CUDA 10.0. It would be great if I could also offer you real dlls for linux. But I don't know if there are any problems with cuda support among the distributions.

In this project I provide an easy entry for .net developers. You can simply install yolo per nuget similar to vcpkg. https://github.com/AlturosDestinations/Alturos.Yolo

**Comment by cenit** [comment]
OpenCV is built on the fly from vcpkg, with the proper recipe.
CUDA is downloaded and installed on the fly from nvidia.com, with the version written on the CI recipe. I'd not redistribute those myself...
dll built with CUDA is the second recipe, without CUDA is the third. Maybe you already have all the files that you need?

**Comment by cenit** [comment]
Also, in a few days, I'd like to finish a recipe on vcpkg for yolo. In that case, you can create a full nuget package directly from vcpkg, with no external intervention nor any added difficulty from the project maintainer

**Comment by tinohager** [comment]
On which position i can found the opencv version in the recipe?

**Comment by cenit** [comment]
the default triplet is x64-windows, then it's just a matter of calling .\vcpkg install opencv

**Comment by tinohager** [comment]
My question is if I can specify the version that will be installed with vcpkg for example opencv 3.4.0

**Comment by cenit** [comment]
to specify the version, you fix the vcpkg tree with a commit id, checking out that particular situation.

**Comment by AlexeyAB** [comment]
@cenit Thanks for PR!
It looks like all is good, so I will merge this PR.

**Comment by cenit** [comment]
Yes, it seems that it also fix some problems user in #2471 have experienced.
Thanks!

**Comment by AlexeyAB** [comment]
@cenit 

> (btw sorry for the problem with the mjpeg-stream, we never review those modifications and I can't even recall which problem they gave me at the beginning, so sorry for the trouble)

Do not pay attention, I constantly break something)

----

It seems the Appveyor for building with CUDA still fails with timeout: https://ci.appveyor.com/project/AlexeyAB/darknet/builds/22812029
Maybe it makes sense to divide the Job (building with CUDA) into two Jobs: Debug & Release in matrix? 
As I understand there is an 1h timeout per one Job in the Appveyor.

----

It would also be great if we could create one cmd/sh file to automatically download and install as much of the necessary software as possible: pthread, opencv, cuda (and may be: vcpkg, cmake, git or even download and run MSVS2017 installer).
The file we can just click on.

**Pull request merged**
