### PR TITLE
CPU implementation of Tracker_optflow

### PR DESCRIPTION
**Pull request by HowardStark**
Created alternative implementation for `Tracker_optflow` by leveraging the OpenCV 3.2 or greater `cv::SparsePyrLKOpticalFlow` class which does not depend on CUDA.

### CODE REVIEW

**Comment by HowardStark** [comment]
@AlexeyAB I would love for this to get merged. The build fails because the `obj_id_to_color` function isn't properly scoped and thus can't be defined in the hpp and then declared in the cpp.

The way you have it now seems to kind of run counter to the idea of a proper API, and I wasn't sure what you thought would be a good pattern to follow for properly scoping `obj_id_to_color`.

**Comment by AlexeyAB** [comment]
@HowardStark Thank you for your Pull Request!

But I can use it only if `darknet.dll` can be compiled without dependencies on OpenCV, and can be used with applications that use any version of OpenCV without recompile `darknet.dll`.

----

The main idea is that - to use the same **darknet.dll/so-file** in different applications without OpenCV or applications with different versions of OpenCV, therefore **`darknet.dll/.so`-library should be able to be built without OpenCV, even if the application using it will use OpenCV**.

So everything that depends on the OpenCV I put in the `src/yolo_v2_class.hpp` file. Trade of idea of proper classical API or ODR in the era of best practices with template functions in header-files - this is a small price for having a library without unnecessary dependencies on the specific version of OpenCV.

----

Otherwise I would leave in the `yolo_v2_class.hpp` definitions not only of the function: `obj_id_to_color()` but also other `class Tracker_optflow`, `class preview_boxes_t`, `mat_to_image_resize()`/`mat_to_image()` ... , and put implementations to the yolo_v2_class.cpp.

**Comment by HowardStark** [comment]
Sorry, I prematurely closed this. I've changed the implementation location back to the header file. 

Beyond that, I think there is a pretty fair amount of value in taking advantage of the CPU implementation. To solve the OpenCV cross-version compatibility concern, what do you think about a specific "OPENCV_320" macro or something along those lines?

**Comment by AlexeyAB** [comment]
Yes, I'll add something like this:
```
#if !defined(CV_VERSION_EPOCH) && CV_VERSION_MAJOR == 3 && CV_VERSION_MINOR >=2
```

Also can you check, what OpenCV version do you use, and can you use this `#include <opencv2/video/tracking.hpp>` instead of this `#include <opencv2/optflow.hpp>`?  https://github.com/AlexeyAB/darknet/blob/2972f8de8e896791dc690206216e7389dc576102/src/yolo_v2_class.hpp#L326-L327

----

As I see there isn't file `opencv2/optflow.hpp` in the last version of OpenCV 3.4.0 that I use.

Also I can't find file `optflow.hpp` in the releases for Windows of OpenCV 3.0.0 and 3.1.0: https://opencv.org/releases.html

Now `class SparsePyrLKOpticalFlow` there is in the `tracking.hpp`: https://github.com/opencv/opencv/blob/master/modules/video/include/opencv2/video/tracking.hpp#L598

**Comment by HowardStark** [comment]
That's interesting. Are you on Windows? I'm on macOS with OpenCV 3.4.0, and on this version it doesn't compile with`#include <opencv2/video/tracking.hpp>`

**Pull request merged**
