### PR TITLE
[CI] update to cuda11.4

### PR DESCRIPTION
**Pull request by cenit**

### CODE REVIEW

**Comment by cenit** [comment]
pr is not ready, there is a bug on linux that requires a fix

**Comment by cenit** [comment]
ok fixed @AlexeyAB

**Comment by andyrey** [comment]
@cenit: Hi Cenit, I saw your fixes for cuda 11.4, I have exactly what you wrote in my /scripts/ files, (that is 11.4 instead 11.2 or 11.3). These are made by CMake, nevertheless, CMake said after configuration: "Could NOT find CUDA: Found unsuitable version "11.4", but required is exact
  version "11.3" (found /usr/local/cuda-11.4). What to do, if I want to stay with cuda 11.4 ?

**Comment by andyrey** [comment]
I reloaded darknet, but the same error after cmake ..

**Comment by cenit** [comment]
can you show full log? 

i think you might have a problem with a dependency (opencv) which was built with cuda 11.3 and now it finds cuda 11.4

**Comment by andyrey** [comment]
@cenit: thank you, you were right. The problem was in my Opencv453, which  couldn't see CUDA. After reinstalling OpenCV properly, Darknet was built either.

**Pull request merged**
