### PR TITLE
clean up before the storm

### PR DESCRIPTION
**Pull request by cenit**
before working on OpenCV4, maybe it is better to have a stable situation with OpenCV3.
Here I removed all the warnings that I could find and added some more guidance inside build scripts. Also, SHARED libraries are now default in all build configurations.

### CODE REVIEW

**Comment by cenit** [comment]
CMakeLists.txt is missing one more line to make it sure that shared is on also in some peculiar configurations. Please wait before merge

**Comment by AlexeyAB** [comment]
@cenit Hi, 

It seems there is a problem, that VCPKG builds OpenCV without ffmpeg by default: https://groups.google.com/forum/#!topic/darknet/FKY73ty_RgQ

**Comment by cenit** [comment]
Thanks for noticing. We have to fix documentation, to do `vcpkg install opencv[cuda,ffmpeg]`

**Comment by cenit** [comment]
I can do it later in this PR

**Comment by AlexeyAB** [comment]
@cenit Hi,

There is generated strange CUDA CC when build.ps1 is used: https://drive.google.com/file/d/1UcZgUQLimcPMxAW5GO6fkYtJvQtX7hMu/view

Issue: https://github.com/AlexeyAB/darknet/issues/2772

**Comment by cenit** [comment]
There are some CMake version that are broken, especially with CUDA 10.1. That's my impression for now

**Pull request merged**
