### PR TITLE
Support building with OpenCV 4

### PR DESCRIPTION
**Pull request by tiagoshibata**
I was asked to port https://github.com/pjreddie/darknet/pull/1348 to this repo. These changes allow building with OpenCV 4. The changes are much smaller than in the original darknet repo (https://github.com/pjreddie/darknet/pull/1348/files), since this repo was already avoiding the raw C API.

I tested building with the Makefile only. There might be work to be done on the CMake project.

### CODE REVIEW

**Comment by SalahAdDin** [comment]
Well, my **Darknet** was compiled with **OpenCV** 3 yet:
```
CUDA-version: 10000 (10010), cuDNN: 7.6.5, CUDNN_HALF=1, GPU count: 1  
 OpenCV version: 3.2.0
 compute_capability = 600, cudnn_half = 0 
```

**Comment by tiagoshibata** [comment]
Does `pkg-config --libs opencv4` work for you? Maybe it's not being picked up by pkg-config (e.g. a custom OpenCV 4 install to `/usr/local` usually isn't picked up by default)

**Comment by SalahAdDin** [comment]
@tiagoshibata https://github.com/opencv/opencv/issues/13154 Maybe it is related to that.

**Comment by SalahAdDin** [comment]
It is not picked, yeah

**Comment by tiagoshibata** [comment]
If it's installed to `/usr/local`, setting `PKG_CONFIG_PATH` should fix it

**Comment by cenit** [comment]
>  There might be work to be done on the CMake project.

@tiagoshibata the CMake toolchain is already OpenCV 4 compatible :)
(also the makefile was ok until OpenCV 4.1, which moved to `pkg-config --libs opencv4` instead of `pkg-config --libs opencv`, thanks for the proper fix!)

**Comment by tiagoshibata** [comment]
Great, you're welcome!

**Comment by SalahAdDin** [comment]
> If it's installed to `/usr/local`, setting `PKG_CONFIG_PATH` should fix it

Well, i think it was installed with **python**, so it is not there.

**Pull request merged**
