### PR TITLE
add CMakeLists.txt and necessary modules

### PR DESCRIPTION
**Pull request by cenit**
build-depends: #2394 

in this PR I propose adding a CMakeLists.txt and some modules which, in perspective, could be more portable (the same script works on Linux, macOS and Windows), manage OpenCV and CUDA easily and enable maintainer to fully drop the 3rd-party folder containing pre-built libraries for windows (using vcpkg on every supported OS, which is again Linux, macOS and Windows)

### CODE REVIEW

**Comment by cenit** [comment]
Forgot to use automatic file detection instead of explicit listing. I will force-push asap with the requested fix

**Comment by cenit** [comment]
I did the requested change. It is not as clean as I'd like, because with automatic discovery also "windows only" C files are captured (and later removed from the list to preserve compatibility with mac and linux). Maybe we can think about moving them to a different folder, if you like this automatic discovery but do not like the manual removal of those.

**Comment by AlexeyAB** [comment]
@cenit Thank you!

> manage OpenCV and CUDA easily and enable maintainer to fully drop the 3rd-party folder containing pre-built libraries for windows (using vcpkg on every supported OS, which is again Linux, macOS and Windows)

It seems it can't find pthread in the `3rdparty/` folder, and it fails on Configuration stage with message in the `CMakeError.log`:

> 
>   CheckIncludeFile.c
> 
> D:\Darknet2\darknet_cmake\darknet\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: pthread.h: No such file or directory [D:\Darknet2\darknet_cmake\darknet\CMakeFiles\CMakeTmp\cmTC_1101f.vcxproj]

Does this necessarily requires `vcpkg`?

Can you add short step-by-step manual to `Readme.md` - how to install `vcpkg` and `Darknet` using Cmake with minimum steps (may be with default parameters)?

**Comment by cenit** [comment]
Technically it could be instructed to search for pre-built libraries also in non-standard locations. Otherwise by default CMake (like pkg-config) has some default paths to look and some files to help finding libs. Of course, package managers (apt, brew, vcpkg, etc...) install libraries and headers in a CMake fully compatible way. Tomorrow I will add quick instructions for all operating systems in the Readme of this PR.

**Comment by AlexeyAB** [comment]
Also it would be nice, if you add that CC 7.5 will be swithed on **only** if CUDA 10.0 or higher is used: https://github.com/AlexeyAB/darknet/pull/2412/files#diff-af3b638bc2a3e6c650974192a53c7291R73
So XNOR-net will use Tensor Cores to speedup.

**Comment by cenit** [comment]
I tried to include all your suggestions for this PR in the latest commit. Unfortunately using your pre-built OpenCV could be a little more difficult than expected, I will check better tomorrow if I can find a quick but still elegant solution

**Comment by cenit** [comment]
Edited comment while you were reading ;)
sorry

**Comment by AlexeyAB** [comment]
@cenit Thanks!

Can we use it with Cmake-GUI?

Currently I get this error when I press "Configure" button. 

image

It seems it still can't find `pthread`.
`CMakeError.log` file:

> Determining if the include file pthread.h exists failed with the following output:
> Change Dir: D:/Darknet2/darknet_cmake_2/darknet/CMakeFiles/CMakeTmp
> 
> Run Build Command(s):C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe cmTC_f1455.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=14.0 /v:m 
> Microsoft (R) Build Engine ўҐабЁЁ 14.0.25420.1
> 
>   cl /c /Zi /W3 /WX- /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:fast /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_f1455.dir\Debug\\" /Fd"cmTC_f1455.dir\Debug\vc140.pdb" /Gd /TC /wd4013 /wd4018 /wd4028 /wd4047 /wd4068 /wd4090 /wd4101 /wd4113 /wd4133 /wd4190 /wd4244 /wd4267 /wd4305 /wd4477 /wd4996 /errorReport:queue D:\Darknet2\darknet_cmake_2\darknet\CMakeFiles\CMakeTmp\CheckIncludeFile.c
> 
>   CheckIncludeFile.c
> 
> D:\Darknet2\darknet_cmake_2\darknet\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): **fatal error C1083: Cannot open include file: pthread.h: No such file or directory** [D:\Darknet2\darknet_cmake_2\darknet\CMakeFiles\CMakeTmp\cmTC_f1455.vcxproj]



----

Even if I add `set(FORCE_CUSTOM_LIBS)` here: https://github.com/AlexeyAB/darknet/pull/2412/files#diff-af3b638bc2a3e6c650974192a53c7291R10

and run this command: `"C:\Program Files\CMake\bin\cmake-gui.exe" %CD:\=\%`

I get the same error:
image

And it looks like that pthread isn't found:
image

And even if I set correct paths:
image

and press "Generate", this leads to an error
image

**Comment by cenit** [comment]
I modified the default behaviour of CMakeLists.txt to prefer 3rdparty folder on windows if not instructed differently. Now CMake-gui, even without manual intervention, should work.
As always, please let me know any remarks you may have

**Comment by cenit** [comment]
as a side note, in the near future I will propose for merge a big load of CMake modules, including one for CUDNN and one for Pthreads on Windows. Whenever they will get accepted, we will be able to remove them from here!

**Comment by AlexeyAB** [comment]
@cenit Hi,

Almost all good.

A few suggestions:

* rename `darklib` to `libdarknet`? To maintain compatibility with software using older versions of `libdarknet.so`
* rename checkbox `COMPUTE_MODEL` to the `CUDA_COMPUTE_MODEL`
* if CUDA is found, then set ON checkbox `ENABLE_CUDA` by default
* set by default CC 3.0 if `CUDA < 10.0`, and set CC 3.0 + 7.5 if `CUDA >= 10.0`
* on Windows, try to search cuDNN by default by using `%PATH%` system environment:  `%PATH%`\include and  `%PATH%`\lib\x64\cudnn.lib
* Also can we somehow set to build executable files in the root-directory `darknet\darknet.exe` instead of `darknet\Release\darknet.exe` directory?

**Comment by cenit** [comment]
- About renaming `darklib`, we have a problem. I cannot declare two different target in a CMakeLists.txt with the same name (darknet the executable and darknet the library). CMake automatically adds ".exe" if necessary as a suffix to executable targets, and "lib" as a prefix to library targets (on *nix, because on windows it adds a ".lib/.dll" extension). So to obtain `libdarknet` I'd have to declare two targets with the same name. I am open to suggestion (maybe we can change the name of the executable?), but unfortunately I don't know an easy way to keep darknet and libdarknet together.

- Done

- Done

- At the moment, my proposed toolchain cannot build for two different CC at the same time. I'd like to defer this work for later, just seeing if CMake is really interesting or not... since I am not proposing any removal of solutions already in place, on the contrary, I am keeping maximum compatibility with them, for now I think one is enough

- FindcuDNN.cmake already looks into significant folders, at the same time accepting some symbolic hints in the spirit of CMake: `HINTS ${CUDA_HOME} ${CUDA_TOOLKIT_ROOT_DIR} PATH_SUFFIXES cuda/include include` for the `cudnn.h` and `HINTS ${CUDA_HOME} ${CUDA_TOOLKIT_ROOT_DIR} PATH_SUFFIXES lib lib64 cuda/lib cuda/lib64 lib/x64` for the library.

- To have the executable in the root folder, it is enought to point the makefile (or the solution) to the install target: from the command line, it is just a matter of `cmake --build . --target install` and there's another added step at the end to copy the targets in the root folder, as a common user would expect, thanks to the final lines of `CMakeLists.txt`

- As I told you, it will be just a matter of `vcpkg install pthreads opencv cuda`. I think that no script is necessary for that. I added some scripts to build correctly `darknet` on windows (`build.ps1`) in many different configurations and on linux, macOS, WSL (`build.sh`)
The fact that you see cuda9 on `vcpkg` does not mean that it is going  to install cuda9, it will point to the latest release available. For what concern cuDNN unfortunately the license forbids to distribute and install it without registration on nvidia website, so that one you'll always have to do by yourself (except for changes in future by nvidia)

**Comment by AlexeyAB** [comment]
@cenit Thanks!

* Can you set this  line `set(default_cuda_compute_model ${CUDA_COMPUTE_MODEL_30} ${CUDA_COMPUTE_MODEL_75})`  there https://github.com/AlexeyAB/darknet/pull/2412/files#diff-af3b638bc2a3e6c650974192a53c7291R45

* And this  line `    HINTS ${CUDA_HOME} ${CUDA_TOOLKIT_ROOT_DIR} $ENV{cudnn}`  there https://github.com/AlexeyAB/darknet/pull/2412/files#diff-b0861fb4eedd65d0bcc014bd34fd7e1eR27
    and this line `    HINTS ${CUDA_HOME} ${CUDA_TOOLKIT_ROOT_DIR} $ENV{cudnn}`  there https://github.com/AlexeyAB/darknet/pull/2412/files#diff-b0861fb4eedd65d0bcc014bd34fd7e1eR33

* Set here `   if(CUDA_COMPUTE_MODEL VERSION_GREATER_EQUAL 70)` since it is actually a Mixed-precision (FP16+FP32) that makes sense only for Tensor Cores CC >= 7.0 https://github.com/AlexeyAB/darknet/pull/2412/files#diff-af3b638bc2a3e6c650974192a53c7291R121

* Also I meant that it would be better to set CUDA enabled by default as it is done for `USE_INTEGRATED_LIB` instead of Remove `CUDA_ENABLE` at all. Can you return the  `CUDA_ENABLE` checkbox back? Just make it enabled by default.

image

----

* Also it doesn't find OpenCV and doesn't set `OPENCV;` definition in the `darknet.sln`
image

While this Yolo_mark find OpenCV and can be built successfully by using this `CMakeList.txt` https://github.com/AlexeyAB/Yolo_mark/blob/master/CMakeLists.txt
so my OpenCV installation and environment system variables `OPENCV_DIR` = `C:\opencv_3.0\opencv\build`  are correct.
image

**Comment by cenit** [comment]
- It's impossible to create a working solution, sorry. The compiler line with your request would read 
```
-gencode arch=compute30;75,code=[sm_30;75,compute_30;75] 
```
which I suppose it doesn't work apart from very strange compiler versions.
I have to think about this problem better, for now I'd like to keep just one CC enabled per build, with an easy way to change it

- Done

- Done

- Done

- Please let me know if it finds now your installation of OpenCV. There was a small bug, it should be solved now

**Comment by AlexeyAB** [comment]
Thanks, now everything looks good!

I will check it also tomorow and merge both these PRs.

----

> * It's impossible to create a working solution, sorry. The compiler line with your request would read
> 
> ```
> -gencode arch=compute30;75,code=[sm_30;75,compute_30;75] 
> ```
> which I suppose it doesn't work apart from very strange compiler versions.
> I have to think about this problem better, for now I'd like to keep just one CC enabled per build, with an easy way to change it

Yes, we will postpone it for the following improvements
* Multiple compute capabilities
* move all OpenCV API calls to the image_opencv.cpp - I will try to do it
* may be the use of CIs: Travis and Appveyor
* ....

Also it would be cool if there was something like this - the installation of the Darknet in 1 click (except cuDNN): OpenCV, CUDA, pthread, MSVS. In order not to understand a lot in the installation of all libraries.

**Comment by cenit** [comment]
I can do the travis&appveyor and also the "one-click" installation. I already have travis&appveyor ready in another branch and the script should be "almost" easy with the CI recipe ;)
Thanks a lot for the great collaboration for both the PRs! The PRs themselves improved really A LOT during the process and the discussions, I found the whole process extremely satisfying.

**Comment by AlexeyAB** [comment]
I checked all. Just 2 fixes and I will merge it.

* Can you also add this line `include_directories("${CUDA_INCLUDE_DIRS}")`
after this line: https://github.com/AlexeyAB/darknet/pull/2412/files#diff-af3b638bc2a3e6c650974192a53c7291R114

* And use `    HINTS ${CUDA_HOME} ${CUDA_TOOLKIT_ROOT_DIR} $ENV{cudnn}  $ENV{CUDNN}`
    * here https://github.com/AlexeyAB/darknet/pull/2412/files#diff-b0861fb4eedd65d0bcc014bd34fd7e1eR27
    * and here: https://github.com/AlexeyAB/darknet/pull/2412/files#diff-b0861fb4eedd65d0bcc014bd34fd7e1eR33

Upper case for system variables is preferably, so later we will remove this `$ENV{cudnn}`.
But currently people who setup cuDNN using my manual use $ENV{cudnn}, so we should still support it for some time.

**Comment by cenit** [comment]
No problem for the additional hint (will do it asap). But why the additional include directory? I didn’t use the deprecated “FindCUDA” module, I used the brand new first class support of CUDA as a language by cmake, through “enable_language(CUDA)”, which does not use these symbols... of course no problem in adding it, but it would look like a leftover from an old CMakeLists.txt IMHO. Did you find any regression?

**Comment by AlexeyAB** [comment]
> But why the additional include directory?

Darknet can't be compiled on my Linux computer without `include_directories("${CUDA_INCLUDE_DIRS}")`
It can't find `#include <cuda_runtime.h>` although command `whereis cuda_runtime.h` find it.
Linux Debian Wheezy x64, CUDA 9.1, gcc 4.9.2.
While OpenCV (using cmake) and other soft (using make) can be compiled with CUDA successfully.

**Comment by cenit** [comment]
Which version of CMake do you have on your system? It would be wonderful if you can open an issue on the [official CMake issue tracker](https://gitlab.kitware.com/cmake/cmake/), with system description and minimum steps to reproduce of course. That way it is possible to track down the problem, which should not exist in the new CUDA support.
Could you please tell me if it works with this include?
```include_directories("${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES})```

If it works, I'd prefer it because it is more future-proof. Besides the fact that it should not be necessary, the previous include is defined only for compatibility reasons.

**Comment by AlexeyAB** [comment]
It works successfully with `include_directories("${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES})`


----

* Linux Debian x86_64 3.16.0-4-amd64
* cmake 3.14.0-rc2 https://github.com/Kitware/CMake/releases/download/v3.14.0-rc2/cmake-3.14.0-rc2.tar.gz
* gcc 4.9.2
* nvcc CUDA 9.1.85
* `whereis cuda_runtime.h` shows `/usr/local/cuda-9.1/include/cuda_runtime.h`


image

**Comment by cenit** [comment]
since it works also with the newer include directive, I added that one.

**Comment by AlexeyAB** [comment]
@cenit 
I just checked, but any of  `include_directories("${CUDA_INCLUDE_DIRS}")` and `include_directories("${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES})` make it possible to compile on linux, but causes an error on Windows )
It seems you are right that it isn't the right way to use it.

**Comment by cenit** [comment]
quick PR to fix it #2461 . Do you know the behaviour on macOS? I don't have mine with me now, but anyway it's "new" and so without any CUDA card in it...

**Comment by AlexeyAB** [comment]
> Do you know the behaviour on macOS?

No, I don't have macOS.

**Comment by AlexeyAB** [comment]
@cenit Hi,

There is some issue with `build.ps1`: https://github.com/AlexeyAB/darknet/issues/2471

**Pull request merged**
