### PR TITLE
add automatic rebase github action

### PR DESCRIPTION
**Pull request by cenit**
in this way, we will be able to just write `/rebase` in a comment in a PR and automatically the PR will be rebased on the newest darknet master branch. This will be very useful to reconsider old Pull Requests which are old and untested with recent modifications

To trigger automatic rebuild we would need to add a personal access token to the repository. We can consider that, or just remember that opening and closing the PR will just trigger a rebuild (see https://github.community/t/triggering-a-new-workflow-from-another-workflow/16250/37 for more details)

### CODE REVIEW

**Comment by cenit** [comment]
@AlexeyAB PR is ready for me. Let me know if you have any question on it

**Comment by AlexeyAB** [comment]
> in this way, we will be able to just write /rebase in a comment in a PR and automatically the PR will be rebased on the newest darknet master branch.

Should I just type `/rebase` right here in the additional empty comment?

> To trigger automatic rebuild we would need to add a personal access token to the repository.

Where should I do this?

**Comment by cenit** [comment]
> Should I just type `/rebase` right here in the additional empty comment?

it will work only once this PR has been merged. 

> Where should I do this?

no need for now. We can add a token later only if really necessary.
For now the pipeline can be triggered just closing and reopening the PR using the button like the one below here, few minutes after writing a /rebase comment in the PR itself

**Comment by AlexeyAB** [comment]
So I can:
1. Write `/rebase`
2. Wait for 5 minutes
3. Close PR
4. Open PR
And it will be rebased.

**Comment by cenit** [comment]
it will be rebased F
after step 2, it will be retested by CI after step 4

**Pull request merged**
