### PR TITLE
Add batch inference on C++

### PR DESCRIPTION
**Pull request by Nuzhny007**
Add method detectBatch to the C++ API and initialization with custom batch_size

### CODE REVIEW

**Comment by AlexeyAB** [comment]
@Nuzhny007 Thanks! Does it do NMS, or do you want to run NMS outside `detectBatch()` function?

**Comment by Nuzhny007** [comment]
>Does it do NMS, or do you want to run NMS outside detectBatch() function?

Outside. If inference runs for crops with overlapping from one frame then NMS will be useful. But you can also pack into batcth different frames. In this case NMS is not nneeded

**Comment by AlexeyAB** [comment]
It is not very logical for other users and it is obvious that NMS is not executed during batch processing. Usually the batch-processing differs only in that several images are processed and it is faster, and nothing else.
I think it is better to add `nms` param to the function, that is enabled by default, so you can disable it in your custom case.

**Comment by Nuzhny007** [comment]
Ok, I will add it

**Comment by Nuzhny007** [comment]
nms added

**Comment by wuzhenxin1989** [comment]
@AlexeyAB @Nuzhny007  detectBatch(image_t img, int batch_size.....)  img is  single image or multiple images

**Comment by Nuzhny007** [comment]
Multiple

**Comment by tuteming** [comment]
how to use detectBatch?
how to define batch_size?
can give a example?

**Comment by Nuzhny007** [comment]
I'm using batch detection in [another project](https://github.com/Smorodov/Multitarget-tracker/blob/master/src/Detector/YoloDarknetDetector.cpp):

```
// Initialization
std::string cfg_filename = "yolov4.cfg";
std::string weight_filename = "yolov4.weight";
int gpu_id = 0;
int batch_size = 2;
Detector detector(cfg_filename, weight_filename, gpu_id, batch_size);

// Detection
std::vector<cv::Mat> frames;
// TODO: Fill frames here...
assert(batch_size == frames.size());
image_t detImage;
FillBatchImg(frames, detImage);
cv::Size netSize(detector.get_net_width(), detector.get_net_height());
std::vector<std::vector<bbox_t>> result_vec = m_detector.detectBatch(detImage, batch_size, netSize.width, netSize.height, confidenceThreshold, true);
// TODO: Draw boxes on frames here

// Service function
void FillBatchImg(const std::vector<cv::Mat>& batch, image_t& detImage)
{
	cv::Mat m_tmpImg;
	std::vector<float> m_tmpBuf;

	detImage.w = m_netSize.width;
	detImage.h = m_netSize.height;
	detImage.c = 3;
	assert(detImage.c == 3);
	size_t imgSize = static_cast<size_t>(detImage.w * detImage.h * detImage.c);
	size_t newSize = batch.size() * imgSize;
	if (newSize > m_tmpBuf.size())
		m_tmpBuf.resize(newSize);
	detImage.data = &m_tmpBuf[0];

	for (size_t i = 0; i < batch.size(); ++i)
	{
		if (batch[i].cols == m_netSize.width && batch[i].rows == m_netSize.height)
			m_tmpImg = batch[i];
		else
			cv::resize(batch[i], m_tmpImg, m_netSize, 0, 0, cv::INTER_LINEAR);

		float* fImgStart = detImage.data + i * imgSize;

		const int h = m_tmpImg.rows;
		const int w = m_tmpImg.cols;
		constexpr float knorm = 1.f / 255.f;
		for (int y = 0; y < h; ++y)
		{
			for (int c = 0; c < 3; ++c)
			{
				const unsigned char* data = m_tmpImg.ptr(y) + 2 - c;
				float* fdata = fImgStart + static_cast<ptrdiff_t>(c * w * h) + static_cast<ptrdiff_t>(y * w);
				for (int x = 0; x < w; ++x)
				{
					*fdata = knorm * data[0];
					++fdata;
					data += 3;
				}
			}
		}
	}
}

```

**Comment by tuteming** [comment]
thanks

**Comment by iAmJuan550** [comment]
Can you create a Python example for this?

**Comment by Nuzhny007** [comment]
I writed C++ example after reading python code. But just now I'm have only phone and can't find it

**Comment by musingxu** [comment]
when I used detectBatch, the result of inference is wrong. The only first image of batch images is right. Has anyone encountered the same issue?

**Comment by LouisDong1995** [comment]
nice code @Nuzhny007 ,but i use you code detected with cpu, Time was same with detect one by one, even more. My CPU has 12core, but run with 1 core. I want know how to less my time or it is necessary to run on GPU? Thanks a lot.

**Pull request merged**
