### PR TITLE
Added docker support + 1 command installation using docker-compose

### LINKED ISSUE #3121: Dockerized Darknet [low priority]
I thought I would share this with the watchers:

https://github.com/Christopheraburns/yolo-docker

Dockerized version of darknet.  Specifically built to run on AWS Sagemaker, but can be modified to run on any machine that has latest CUDA drivers (and NVIDIA GPU of course).

Train your own model and replace the libyolo_volta.so  (as well as .cfg, .data, .names and weights) with your version.

### LINKED ISSUE #6960: Dockerfile on project
To anyone can run project without errors. I think you should write a Dockerfile for anyone running on docker instead of install dozens of libs

### LINKED ISSUE #8140: Docker version of Darknet
I want to run YOLO V3 and V4 under the docker container, I wonder if there is any docker version of AlexeyAB darknet, something that is comprehensive like this repository.

### PR DESCRIPTION
**Pull request by mhwahdan**
@AlexeyAB 
@cenit 
@WongKinYiu

Added docker support for yolo using 2 docker files one for building using the gpu and the other for the cpu.

Also added 1 command installation utility using docker-compose:
so the installation steps are :
1. clone the repo and enter it's directory
2. Configure the make file and modify any thing you want.
3. make sure to have docker installed on your OS and install it if not from this link : [docker installation link](https://docs.docker.com/engine/install/)
4. run the following command 
    -   for cpu: `docker-compose run yolo-cpu bash`
    -    for gpu: `docker-compose run yolo-gpu bash`

After that you will find your self in a bash terminal on a linux container logged in with username yolo and password yolo.
Now you can run any command you need from the yolo documentation.

The docker-compose file will allow you to modify the enviroment as you want whether you want to bind directories, expose ports, connect multiple gpus and much more.

That commit will successfully complete the mile stone of having easy installation of the Darknet.

fixes #6960 , fixes #8140 , fixes  #3121 , fixes #7644

### CODE REVIEW

**Comment by mhwahdan** [comment]
@AlexeyAB
@cenit
@WongKinYiu

please approve the workflow

**Comment by mhwahdan** [comment]
@AlexeyAB
@cenit
@WongKinYiu

Ready to merge

**Comment by cenit** [comment]
the build is not performed inside a container but is left to the user. Shouldn't it be better to ensure binary compatibility?

**Comment by cenit** [comment]
also, this PR does not fix #7644

**Comment by mhwahdan** [comment]
> the build is not performed inside a container but is left to the user. Shouldn't it be better to ensure binary compatibility?

No, the build is performed inside the container, the user has only to modify the Makefile and the container will build yolo inside the container so binary compatibility is ensured.

> also, this PR does not fix #7644 and is a minor subset of #4148 which never got merged

it will allow the user to setup yolo on windows using containers instead of MSbuilds and this docker build
Also my PR made a docker file inside the repo it's self so the container's distribution can be easily controlled and monitored and we can ensure that by adding workflows for testing it

**Comment by mhwahdan** [comment]
we use a dockerfile to build the container and yolo inside of it by copying the source code and compiling it inside the container using make

**Comment by mhwahdan** [comment]
@AlexeyAB
@cenit
@WongKinYiu

please merge

**Comment by cenit** [comment]
merging a PR might take some time and is not guaranteed in any case :)
please be patient

**Comment by mhwahdan** [comment]
great
If it helps I can provide a demonastration of it running

**Comment by mhwahdan** [comment]
@AlexeyAB
please approve the work flow

**Comment by mhwahdan** [comment]
@AlexeyAB

Please approve the workflow and tell me if you lke to have a demo of the setup and running

**Pull request merged**
