### PR TITLE
update to cuda 11.5

### PR DESCRIPTION
**Pull request by cenit**
Fixes: #8001

### CODE REVIEW

**Comment by cenit** [comment]
@AlexeyAB any question on this PR?

**Comment by AlexeyAB** [comment]
@cenit Hi, Thanks! I think PR is good, so please merge it.

**Comment by AlexeyAB** [comment]
@cenit Also this is strange that each day I get an email `[AlexeyAB/darknet] Run failed: Darknet Continuous Integration - master (359001d)` or `[AlexeyAB/darknet] Run failed: Darknet Continuous Integration, Attempt #2 - master (359001d)` https://github.com/AlexeyAB/darknet/actions/runs/1451070385

That is related to this commit https://github.com/AlexeyAB/darknet/commit/359001d360df2fe8b77ce56c60bb3d48b6d1faea

image

----

image

**Comment by cenit** [comment]
whenever there is a failure in ci you receive an email.
but all of those errors are transient errors and fix themselves in a second try...
it's just unnecessary "spam"
it should worry you only if in the action tabs it just remains red for many days and/or PR are constantly failing checks

**Comment by cenit** [comment]
ok now there is a real error 😢 
i will fix it tomorrow, sorry for the inconvenience

**Comment by cenit** [comment]
fixed :)

**Comment by AlexeyAB** [comment]
@cenit Thanks a lot!

**Comment by cenit** [comment]
you are welcome. On the contrary, sorry for the broken update! I didn't notice the problems during the PR phase because nightly/master continuous integrations run different scripts than PRs (for security reasons, in case a malicious PR happens), so PR do not test all CI steps...

**Pull request merged**
