### PR TITLE
[build.ps1] fix 64bit build with developer powershell for VS19

### PR DESCRIPTION
**Pull request by cenit**
as per title 

@stephanecharette

### CODE REVIEW

**Comment by cenit** [comment]
@AlexeyAB ready for merge for me if CI is ok and @stephanecharette gives positive feedback

**Comment by AlexeyAB** [comment]
@stephanecharette Does it solve your issue?

**Comment by AlexeyAB** [comment]
@cenit 


* For some reason Cmake propose to use CUDA CC 5.5 instead of 8.5 for my RTX 3090 https://en.wikipedia.org/wiki/CUDA#GPUs_supported

* Also can we make Cmake to copy this file https://github.com/AlexeyAB/darknet/blob/master/3rdparty/pthreads/bin/pthreadVC2.dll near to `darknet.exe` file during compilation? (as I understand we need it only if we use Cmake on Windows without VCPKG)

**Comment by cenit** [comment]
if you use build.ps1 script you have darknet in the root folder and also the dll next to it.
For CC 5.5, which cmake are you using? and which driver?
cmake itself should find the best CC for every card, so if it's wrong it might be because your cmake is too old.
You can override in any case with cmake cache variable "CMAKE_CUDA_ARCHITECTURES" (put 85 for 8.5)

**Comment by cenit** [comment]
I'm also waiting for @stephanecharette reply, also on discord I had no feedback.
But I was able to replicate his problem and with these fixes it works now.
I hope it's ok for him too

**Comment by AlexeyAB** [comment]
> For CC 5.5, which cmake are you using? and which driver?

I get CC 5.2 for my RTX 3090 for two configurations:

image

**Comment by cenit** [comment]
https://cmake.org/cmake/help/latest/variable/CMAKE_CUDA_ARCHITECTURES.html

this is the guide about the variable.
i was wrong about the selection of the best architecture of the current installed card, it is automatically populated now by the default architecture of the currently installed nvcc 

shall we set up a different default?

**Comment by cenit** [comment]
@AlexeyAB do you think that fixes on CMAKE_CUDA_ARCHITECTURES should belong to this PR?
or maybe we can discuss it in a new one?

Shall we merge this PR for now?

**Comment by AlexeyAB** [comment]
@cenit 

> it is automatically populated now by the default architecture of the currently installed compiler (nvcc)

I think this is good behavior, the lower the CC, the better, because Darknet can be compiled on one PC, but can be used on another PC.

**Comment by cenit** [comment]
> @cenit 
> 
> 
> 
> > it is automatically populated now by the default architecture of the currently installed compiler (nvcc)
> 
> 
> 
> I think this is good behavior, the lower the CC, the better, because Darknet can be compiled on one PC, but can be used on another PC.

ok good! i had the impression you preferred a different behavior. In any case users can override it with a number or a list (ex: 52;60;75 to build for three CC)

**Pull request merged**
