### PR TITLE
Make "darknet.exe classifier predict" behavior same as "darknet.exe c…

### PR DESCRIPTION
**Pull request by vinjn**
…lassifer validate"

### CODE REVIEW

**Comment by vinjn** [comment]
@AlexeyAB can you check? I know classifier is not a popular use case for darknet..

**Comment by vinjn** [comment]
@AlexeyAB ~

**Comment by AlexeyAB** [comment]
@vinjn Hi, ok.

I hope this will not cause questions to users, why the original repository and my repository give different results: https://github.com/pjreddie/darknet/blob/master/examples/classifier.c#L589

**Comment by vinjn** [comment]
I think it's a bug in original repo since `letterbox_image` is called only once in that file.

**Pull request merged**
