### PR TITLE
ZED Camera support improvements

### PR DESCRIPTION
**Pull request by adujardin**
- Feat. : Basic cmake support for the ZED, might need to test on more configurations, especially with a CUDA version that doesn't match the ZED SDK one...
(On Ubuntu 16.04, the cmake from the repo is too old to handle CUDA natively, it requires a manual update)

- Fix : The definition is `ZED_STEREO` in the code but was `ZED_CAMERA` in the Makefile

### CODE REVIEW

**Comment by cenit** [comment]
hi @adujardin, what do you mean with "cmake from the repo is too old"? I wrote the CMakeLists.txt trying to aim for the most up-to-date cmake language and best practices. Please let me know which kind of improvements you'd like to see. If you mean the cmake binary in ubuntu 16.04 which is too old, then I agree, but it is very easy to update and we can put a easy-install script here also if needed. @AlexeyAB is requesting it to me since a long time 🤣 
Of course we can expand the CI coverage. I also have already some fixes for windows in the Stb PR. Many more will come, especially because I am targeting a direct integration with vcpkg, which is just starting (you can already find a port there, but it's not fully working, i will iterate on it quickly)

btw: glad to see you here, I saw your fork and your great work on zed cameras, I hope you aim for seamless upstream integration like the one I almost reached!

**Comment by adujardin** [comment]
Hi @cenit, don't get me wrong, your cmake implementation is very good. 
I meant the apt repository yes :slightly_smiling_face:

You're right, it's not difficult to update but it should probably be mentioned in the doc somewhere eventually.

**Comment by AlexeyAB** [comment]
@adujardin Hi Aymeric

Thanks for your contribution! Everything works perfectly!

**Comment by adujardin** [comment]
If needed [this script](https://gist.github.com/adujardin/6b37d2b9a3a0d64254b57e7d199cc806) will easily update the cmake version on Linux without messing with the system version one (A lot of dependencies want the cmake apt package to be installed, ROS for instance).

**Pull request merged**
