### PR TITLE
Amend best_map during training to emulate mAP@[.5:.95]

### PR DESCRIPTION
**Pull request by willbattel**
This is a followup to #2923 that introduced the feature of saving the weights with greatest mAP during training. A problem that I have noticed is that, because it only validates `mAP@0.5`, the mAP scores for greater IoU thresholds are being sacrificed and negatively affecting the overall `mAP@[.5:.95]` score.

On one hand, I would like to have it run all ten IoU thresholds. On the other hand, this would slow down training significantly.

The compromise I am proposing in this PR is to average two IoU thresholds: 0.60 and 0.85, which are the first the third quartiles of the range and sufficiently represent the `mAP@[.5:.95]` spread without pausing to compute all ten scores every hundred iterations.

I am currently testing this change on my own dataset. I will report the results here and mark the PR as "ready for review" upon conclusion.

### CODE REVIEW

**Comment by willbattel** [comment]
Here are my test results. I ran two identical training sessions, one that does not include this change (labeled "before") and one that does include this change (labeled "after"). Notice that the upper IoU thresholds noticeably benefit from this change, as does the overall `mAP@[.5:.95]` score, sacrificing only a few points at the lowest thresholds.

|        | mAP@[.5:.95] | mAP@0.50 | mAP@0.55 | mAP@0.60 | mAP@0.65 | mAP@0.70 | mAP@0.75 | mAP@0.80 | mAP@0.85 | mAP@0.90 | mAP@0.95 |
|--------|--------------|----------|----------|----------|----------|----------|----------|----------|----------|----------|----------|
| Before | **30.03%**       | 69.65%   | 65.33%   | 55.82%   | 44.53%   | 33.49%   | 18.05%   | 9.76%    | 3.15%    | 0.49%    | 0.01%    |
| After  | **30.78%**       | 64.29%   | 62.42%   | 57.02%   | 44.80%   | 35.81%   | 24.40%   | 12.77%   | 5.58%    | 0.74%    | 0.00%    |

This confirms my theory regarding validation during training, and I recommend that this change be considered for merging.

**Comment by willbattel** [comment]
@AlexeyAB what are your thoughts on this? We're using this change in all of our training now, and our best mAP is consistently better than before.

**Comment by willbattel** [comment]
@AlexeyAB can I get your opinion on this? I've been using this the past few months for all training and it seems to consistently improve overall accuracy. The original implementation favored mAP@0.5 too heavily so box precision was poor.

**Comment by willbattel** [comment]
Alternatively, I suppose you could just use one mAP for validation but change it from 50 to 75... maybe that's simpler.

**Comment by skaldesh** [comment]
Great PR! Thanks for this
@AlexeyAB I second this

**Pull request closed without merging**
