### PR TITLE
add setup prerequisite script scaffolding

### PR DESCRIPTION
**Pull request by cenit**
as per title, this is a work in progress of the promised script. Let's track here requests, features, ...
I know that it does not work as of now, it's just to give you an idea

### CODE REVIEW

**Comment by AlexeyAB** [comment]
@cenit Hi,

Some ideas:

For example, there are two ps1/sh/cmd files, that can be run just by clicking on them:

1. One to build Darknet if there are already installed OpenCV, CUDA, cuDNN, MSVS (and use local pthread, stb)

2. One to build Darknet and all possible dependecies: OpenCV, CUDA, cuDNN, MSVS, pthread, stb

Maybe you have a better suggestion.

**Comment by cenit** [comment]
Green marks for CI require #3738 to be merged

**Comment by AlexeyAB** [comment]
@cenit Hi,
Is this PR ready? So I will merge it.

**Comment by cenit** [comment]
@AlexeyAB Hi!
It is, but any feedback would be nice.
There is also no documentation for now on how those scripts work and maybe it's better if I prepare it before publishing them, otherwise no user will understand them. They have some flags at the beginning, to turn on/off features, but maybe they are not very clear...

**Comment by AlexeyAB** [comment]
@cenit Hi,
Thanks, Yes, I will wait for doc.
Also it would be nice to have possibility to run it without any changes and flags, just if somebody don't know how to use it - just click `setup.ps1/sh` )

**Comment by cenit** [comment]
yes you can run without modifying flags. The defaults should be ok, apart from the fact that it does *not* install CUDA. I still have not figured out a proper way to decide automatically if it is good or not to install it...

**Comment by AlexeyAB** [comment]
@cenit I think CUDA should be installed, if it isn't installed yet. Because Darknet without CUDA makes little sense.
We only need to warn that the CUDA will be installed.

**Comment by cenit** [comment]
You are right, but many people install darknet only to try it out and they don’t have  gpu. I would not want to mess with their system.

**Comment by AlexeyAB** [comment]
@cenit Hi,
It seems something wrong with `macOS - clang - vcpkg` in TravisCI for the last commits: 
```
Error: gcc 9.2.0_1 is already installed
To upgrade to 9.2.0_2, run `brew upgrade gcc`.
The command "eval brew install gcc && brew install yasm && unset CC && unset CXX" failed 3 times.
The command "travis_retry eval "${MATRIX_EVAL}"" failed and exited with 1 during .
```

**Comment by cenit** [comment]
ok thanks for the ping. Let me examine the situation. Something must have changed in travis

**Comment by AlexeyAB** [comment]
@cenit Thanks!
Can I merge this PR?

**Comment by cenit** [comment]
The scripts were still a work in progress. Let me work on them a little bit. I almost forgot this branch, sorry, I want to check if they still work. Tomorrow I will give you the green/red flag (in case of red flag I will prepare a separate pr for the CI fixes)

**Comment by cenit** [comment]
you can merge it in order to have also feedback from users.
I moved the scripts in the scripts/ subfolder, in order to hide them a little bit while they go out of "beta"

**Comment by cenit** [comment]
in this way you can fix the red cross on the CI, which I am sure is becoming frustrating

**Comment by AlexeyAB** [comment]
@cenit Thanks! 
But it seems there is still red cross on the CI.

**Comment by cenit** [comment]
it might be just a cache problem on travis. I triggered a reset and a rebuild. It might take *a lot* to finish those builds, but I expect a green mark afterwards

**Comment by cenit** [comment]
ok it was not a problem on our side
libpng has been broken on vcpkg. I am opening a PR there as of now

**Comment by cenit** [comment]
this is the broken PR (already merged, unfortunately): https://github.com/microsoft/vcpkg/pull/8716

**Comment by AlexeyAB** [comment]
@cenit Thanks. So just will wait for fixing vcpkg.

**Comment by cenit** [comment]
yes. Here it is my PR there, I don't know how much time it will take to get it approved

https://github.com/microsoft/vcpkg/pull/9198

**Pull request merged**
