### PR TITLE
add support for Windows PowerShell

### PR DESCRIPTION
**Pull request by cenit**
I might have found what failed on your system @AlexeyAB . I tried build.ps1 script only on PowerShell v6 and v7, on v5 it was failing.
Is it better now? Can you please test the script as before?

### CODE REVIEW

**Comment by cenit** [comment]
@AlexeyAB the improved build script should answer your two main points:
1) it does not close if erroring out and you are not running in a shell already opened
2) it should work also on Windows PowerShell v5 (it was broken previously on v5, sorry for not testing that old version, I tried only v6 and v7)

**Comment by AlexeyAB** [comment]
@cenit Hi, Thanks!

Yes, now the installation process goes on, but at some point the window closed and I cannot find the darknet.exe file.
I see `vcpkg` folder, `build_release` folder, `DarknetConfig.cmake.in` file. Total size of the entire directory ~2GB.

Log:
[vcpkg-manifest-install.log](https://github.com/AlexeyAB/darknet/files/6468142/vcpkg-manifest-install.log)
[CMakeCache.txt](https://github.com/AlexeyAB/darknet/files/6468144/CMakeCache.txt)

**Comment by cenit** [comment]
can you please re-run build script from a powershell already opened?
i might have missed a point of failure and the script closes without stopping on the message...
vcpkg will restart from where it left over in case you fear of loosing a lot of time

**Comment by cenit** [comment]
i also need those files from your pc

C:\Users\HP\Desktop\Projects\yolo_test2\f4e21bd86985adb5da265e493eb512abe0381e7c\darknet-f4e21bd86985adb5da265e493eb512abe0381e7c\vcpkg\buildtrees\protobuf\install-x64-windows-dbg-err.log

C:\Users\HP\Desktop\Projects\yolo_test2\f4e21bd86985adb5da265e493eb512abe0381e7c\darknet-f4e21bd86985adb5da265e493eb512abe0381e7c\vcpkg\buildtrees\protobuf\install-x64-windows-dbg-out.log

**Comment by AlexeyAB** [comment]
@cenit 
[install-x64-windows-dbg-err.log](https://github.com/AlexeyAB/darknet/files/6469268/install-x64-windows-dbg-err.log)

install-x64-windows-dbg-out.log is empty

**Comment by cenit** [comment]
error: Filename longer than 260 characters

please run build.ps1 from a shorter folder, maybe just c:\darknet

i will add a diagnostics at the beginning and warn users in case something like your problem happens, hinting also a solution

**Comment by cenit** [comment]
@AlexeyAB please try the new version. It should alert you when path is too long. And as the previous one should work ok if the path is shorter (please try something c:\darknet as i was saying)

**Comment by AlexeyAB** [comment]
@cenit 

Thanks, now it works well
* without CUDA/cuDNN/OpenCV
* with CUDA11.02 / cuDNN8.1.1 / OpenCV4.5.1

----

Now it gives out warning even for a not long path, which is very often used `C:\Users\HP\Desktop\Projects\yolo_test3`
* Is this a ninja problem? 
* Can we fix it somehow (besides the warning)?
* Also can we add CI or GitHub-action to test that `./build.ps1` works well with default setting/Powershell/... ?
* Also why does it install: `protobuf:x64-windows, hdf5:x64-windows, leptonica:x64-windows, tesseract:x64-windows, libwebp:x64-windows, openssl:x64-windows, `  ? Do we really need all this libs?

image

**Comment by cenit** [comment]
> @cenit 
> 
> 
> 
> Thanks, now it works well
> 
> * without CUDA/cuDNN/OpenCV
> 
> * with CUDA11.02 / cuDNN8.1.1 / OpenCV4.5.1
> 
> 

glad to hear that :)



> 
> ----
> 
> 
> 
> Now it gives out warning even for a not long path, which is very often used `C:\Users\HP\Desktop\Projects\yolo_test3`
> 

i put a very conservative length. Better safe than sorry. We can test "how big" we can go without breaking everything


> * Is this a ninja problem? 

this is a windows problem. Traditionally paths on windows have a maximum length of 255 chars. Windows 10 can go beyond that but to maintain compatibility it is still hidden. No ninja problem, just a windows terrible heritage 

> 
> * Can we fix it somehow (besides the warning)?
> 

nope. you have to live with it. It's being worked on in windows, but backwards compatibility is making it very complicated


> * Also can we add CI or GitHub-action to test that `./build.ps1` works well with default setting/Powershell/... ?
> 

CI is already using build.ps1 in all its tests. The fact is that interactivity is not permitted on CI, so build.ps1 is always called with the -DisableInteractive parameter

> * Also why does it install: `protobuf:x64-windows, hdf5:x64-windows, leptonica:x64-windows, tesseract:x64-windows, libwebp:x64-windows, openssl:x64-windows, `  ? Do we really need all this libs?
> 
> 

to build opencv+ffmpeg with a reasonable amount of features you need all of those dependencies


> 
> image
> 
>

**Comment by cenit** [comment]
if you meant testing older powershell in CI, that's a little bit more difficult, because github actions tends to live bleeding edge and so they have PowerShell 7 on all instances...
but now we are ready to support also pwsh5, i hope it's enough without going too far in the past

**Comment by AlexeyAB** [comment]
@cenit Ok, thanks!

Also what are the main differences/similarities/advantages of `VCPKG` over `conda / pip`? 
As far as I understand, conda is not just for Python (package, dependency and environment management for any language - Python, R, Ruby, Lua, Scala, Java, JavaScript, C / C ++, FORTRAN, etc.).

**Comment by cenit** [comment]
> to build opencv+ffmpeg with a reasonable amount of features you need all of those dependencies

also, we do not decide anything about those dependencies. The opencv portfile contains all those informations about how to build it properly from sources. They might change in future but we will not have to change anything on our side

**Comment by cenit** [comment]
> @cenit Ok, thanks!
> 
> 
> 
> Also what are the main differences/similarities/advantages of `VCPKG` over `conda / pip`? 
> 
> As far as I understand, conda is not just for Python (package, dependency and environment management for any language - Python, R, Ruby, Lua, Scala, Java, JavaScript, C / C ++, FORTRAN, etc.).

conda and pip are not meant for c/c++. 
vcpkg is and it's becoming a de-facto best solution for building libraries in a cross platform way.

with a single command you can install any library on any os.

we use vcpkg to serve our dependencies, but users can use vcpkg to get darknet too (in that case it is not always the latest version, it is updated whenever i do a new release there - pointing to a newer commit from your repo of course).
it's validated so it goes under some tests


by the way, why you do not use PRs yourself when pushing to your repo? i know it might sound strange to you, but please try it, you will find that it makes work smoother and easier. You can merge your own PR at the end when you feel safe about it

**Comment by AlexeyAB** [comment]
> by the way, why you do not use PRs yourself when pushing to your repo? i know it might sound strange to you, but please try it, you will find that it makes work smoother and easier. You can merge your own PR at the end when you feel safe about it



Yes, I know, that the best way is to use separate branches and Merge/do PR when it is stable )  Yes, I think it can be better for public project with big community. 
I do this for production, while I usually don't do it for research.

----

Just they said about conda https://docs.conda.io/en/latest/
> Package, dependency and environment management for any language—Python, R, Ruby, Lua, Scala, Java, JavaScript, **C/ C++**, FORTRAN, and more.

**Comment by cenit** [comment]
> Just they said about conda https://docs.conda.io/en/latest/
> 
> > Package, dependency and environment management for any language—Python, R, Ruby, Lua, Scala, Java, JavaScript, **C/ C++**, FORTRAN, and more.

i do not know any real world example that uses conda to guide users to build the project from sources. only vcpkg or conan (or they just give up and list you dependencies to have to build the code)
do you know any real world example?

**Comment by Razkolnikova** [comment]
I am personally still getting an error on Powershell v5. Would updating it help? 
error

**Comment by cenit** [comment]
this does not look like latest release, so yes updating is for sure beneficial.
also please post full logs from the very first line in text mode not pictures

**Comment by cenit** [comment]
> I am personally still getting an error on Powershell v5. Would updating it help? 
> 
> error
> 
> 

can you please retry with latest version from master? we just added some debug informations to verify your problems

**Pull request merged**
