### PR TITLE
fixes for clang/mac

### PR DESCRIPTION
**Pull request by cenit**

### CODE REVIEW

**Comment by cenit** [comment]
static builds are otherwise broken on newer clang versions, mainly due to uninitialized global variable used as extern

**Comment by cenit** [comment]
I also reverted #3389 implementing a check on CMake version. Now only if cmake version is >3.11 (instead of >3.9) we enable OpenMP. Otherwise the support is broken and can damage builds if CUDA is also available

**Comment by AlexeyAB** [comment]
@cenit Is this PR ready?

Also can you look at these messages https://github.com/AlexeyAB/darknet/issues/3385#issuecomment-501445446 and https://github.com/AlexeyAB/darknet/issues/3385#issuecomment-501465978  ?

**Comment by cenit** [comment]
Hi! Yes, I took the opportunity to clean up the README about removing manual cuda compute capability (not necessary anymore, now we have automatic detection inside cmake) and to invert logic for vcpkg ("use_vcpkg" instead of "avoid_vcpkg" as the name of the variable). Also the automatic dll copying was not working anymore since recently dll got moved and so I fixed it.
PR should be ready :)

**Comment by cenit** [comment]
https://github.com/AlexeyAB/darknet/pull/3389#issuecomment-501636035

Another confirmation that the pr should be ready

**Pull request merged**
