### PR TITLE
remove appveyor CI

### PR DESCRIPTION
**Pull request by cenit**
As per subject. Since it has become so slow, it's always failing. Better to fully remove it. They are fully superseded by GitHub Actions, which we can expand further if you want.
Also, as promised, we can extend CI through Azure Pipelines soon (next PR)

### CODE REVIEW

**Comment by cenit** [comment]
If accepted, you should also remove permissions to appveyor ci from this repository, inside this repository's settings, then webhooks, then appveyor -> delete

**Comment by cenit** [comment]
Also, please tell me if you want some more configurations tested before removing appveyor, so that I can include them inside this PR

**Comment by AlexeyAB** [comment]
As I see AppVeyor is in the Integrations, not in the Webhooks.
Ok, I disabled AppVeyor.

**Comment by AlexeyAB** [comment]
> Also, please tell me if you want some more configurations tested before removing appveyor, so that I can include them inside this PR

If possible:
* CygWin + MSVS
* no-CUDA + CUDA
* no-OpenCV + OpenCV

As I understand, we can't test cuDNN on Windows.

No need to test multiple versions of CUDA

**Comment by cenit** [comment]
Ok sure, maybe we already have them?
1. "CygWin + MSVS" what do you mean with this config? There is already Cygwin but Cygwin uses gcc to build darknet, not MSVC.
2. win-integrated-libs and win-intlibs-cuda are already the same build, one without and one with cuda. "Integrated libs" means using libraries from 3rdparty folder (stb and pthreads from your repo and not from system). Same for win-vcpkg and win-vcpkg-cuda (one with cuda, one without), just using external 3rd party libraries and not yours
3. win-integrated-libs, win-intlibs-cuda, win-intlibs-cpp are without opencv, win-vcpkg and win-vcpkg-cuda are with opencv. Do you need any other combination?
4. cuDNN is tested on windows inside win-vcpkg-cuda build :)

**Comment by AlexeyAB** [comment]
1. Just 2 compilers: CygWin, MSVS. I removed `+` )

2. Ok

3. Can we test compilationn of Win-OpenCV but without vcpkg?

4. Good

**Comment by cenit** [comment]
can we consider 1. done?

3. Ok sure, I can try to see if we can perform a silent installation of OpenCV downloaded from its website, then it should be easily done

**Comment by AlexeyAB** [comment]
1. Yes
2. Ok

**Comment by AlexeyAB** [comment]
@cenit Hi,

I get an error in GitHub Actions for ` Install CUDA`: https://github.com/AlexeyAB/darknet/runs/653262387


> Reading state information...
> E: Unable to locate package cuda-compiler-10-2
> E: Unable to locate package cuda-libraries-dev-10-2
> E: Unable to locate package cuda-driver-dev-10-2
> E: Unable to locate package cuda-cudart-dev-10-2
> E: Unable to locate package cuda-curand-dev-10-2
> ##[error]Process completed with exit code 100.

**Comment by cenit** [comment]
there are some 504 errors before, like
```
Err:17 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
77
  504  Gateway Timeout [IP: 152.195.19.142 80]
```
looks like nvidia servers are under a traffic hit? Or maybe we will soon see a new cuda release and they are updating them? :)

**Comment by cenit** [comment]
on travis there is the same problem

https://travis-ci.org/github/AlexeyAB/darknet/builds/684297490

all cuda-enabled builds are failing unfortunately

**Pull request merged**
