### PR TITLE
move Stb lib to 3rdparty folder

### PR DESCRIPTION
**Pull request by cenit**
as described [here](https://github.com/Microsoft/vcpkg/pull/5648), stb is already present in vcpkg as a standalone port. Since darknet builds successfully with the most up to date stb library, I moved those headers away from the main src tree and relegated them inside the 3rdparty folder, easing also the port complexity while at the same time maintaining best compatibility with already installed headers and/or injecting them inside toolchain if missing system-wide.
I had to make changes in the makefile (legacy) and in the CMakeLists.txt (new) to support this change, but in perspective I think this should also ease the mainteinance on darknet code itself, since Stb is just an image library which we include but we do not customize in any way, while being very big by itself.
Please let me know your opinion on this topic, which I discovered while working through darknet publication on vcpkg.
Also, again, this PR is not very well tested, so please let me also know if you experience any problem

### CODE REVIEW

**Comment by AlexeyAB** [comment]
@cenit Thanks for PR!

Yes, I think it is a good idea to be able to use either the newest version of the library (stb, pthreads) with new bug fixes from the VCPKG or the old well tested one from the `3rdparty` folder.

I will this PR.

Also, can you look at this issue (installation opencv[cuda] by using vcpkg), is it related to some bug in VCPKG? https://github.com/AlexeyAB/darknet/issues/2569

**Comment by cenit** [comment]
No bugs in vcpkg. It is bug free :rofl: . Just a system config issue. I hope it works now for him

**Comment by AlexeyAB** [comment]
@cenit Hi,

Why did you remove `cmake/Modules/FindDarknet.cmake` ?
Also it seems there is an issue with build.ps1: https://github.com/AlexeyAB/darknet/issues/2615

**Comment by AlexeyAB** [comment]
@cenit Hi,

It looks like something wrong when Appveyor try to compile Darknet: https://ci.appveyor.com/project/AlexeyAB/darknet/builds/23170385/job/b08hwls59o0mxymv#L745

> LINK : fatal error LNK1104: cannot open file '**optimized**;C:\projects\vcpkg\installed\x64-windows\lib\pthreadVC2.lib;debug;C:\projects\vcpkg\installed\x64-windows\debug\lib\pthreadVC2d.lib' [C:\projects\darknet\build_release\uselib.vcxproj]

**Comment by cenit** [comment]
Hi @AlexeyAB, 
I removed FindDarknet.cmake because it is not necessary. It was a leftover from my previous usage of darknet, now that the buildsystem produces a native and self-populated DarknetConfig.cmake it is not needed anymore. When a library is built by CMake, the best practices are to use <PackageName>Config.cmake and not a custom-made find<PackageName>.cmake, which is necessary for non-cmake-built libs.
To build a dynamic library you just have to define a common CMake-understood symbol, which is commented at the beginning of build.ps1. Without a "forced" SHARED option, now that library can be either static or shared depending on user mode.
There's a bug in the findpthread_windows.cmake which is already fixed in this PR
I am already trying to fixing the uncovered bugs about cuda compute capabilities. A huge thanks to the users for uncovering them

**Comment by cenit** [comment]
for what concern the  `optimized;C:\projects\vcpkg\installed\x64-windows\lib\pthreadVC2.lib;debug;C:\projects\vcpkg\installed\x64-windows\debug\lib\pthreadVC2d.lib` string, well this is a perfecly fine string for a library in cmake. It means that the one following optimized is a release lib, the one following debug is a debug lib

**Comment by AlexeyAB** [comment]
@cenit Hi, Thanks for PR

> Without a "forced" SHARED option, now that library can be either static or shared depending on user mode.

Does it mean that it is static-library by default?
Why not make it shared by default?

It would also be nice if we could specify at least 2 CUDA Compute Capabilities:
* one CC by default `3.0`
* and one CC to choose from - that is set `7.5` by default on CUDA 10, or `7.0` on CUDA 9

Also it seems there is an issue with `pthreadVC2d.dll not found` when VCPKG is used https://github.com/AlexeyAB/darknet/issues/2636

**Comment by AlexeyAB** [comment]
@cenit I think it would be better to make shared library by default: https://github.com/AlexeyAB/darknet/issues/2670

**Comment by cenit** [comment]
ok, it's just a matter of a define at the beginning of the build scripts, which for now is commented...

**Comment by AlexeyAB** [comment]
@cenit Hi,

There is some issue with build.ps1: https://github.com/AlexeyAB/darknet/issues/2388#issuecomment-477251939

**Comment by cenit** [comment]
For the Arcticold problem, I was discussing his problem also on the vcpkg issue tracker. I think it is better if he continues there. The problem anyway is not related to darknet nor vcpkg, but just the very moltitude of opencv installations on his machine.

For what concern cmake and parallel, yes there is a discrepancy. I tailored cmakelists.txt and build.sh for cmake >=3.8, but build.ps1 requires cmake >3.12 (otherwise we can just remove the `--parallel`, but the build would become very slow.
By the way, I also saw that you put SHARED inside the library. Technically it is not the best way to build darknet shared library, it is more of a hack than the real solution, which is to pass the proper flag to cmake during build (-DBUILD_SHARED_LIBS:BOOL=ON), check the first commented line in build.ps1)

**Comment by AlexeyAB** [comment]
@cenit 

I wrote you an email.

----

> For the Arcticold problem, I was discussing his problem also on the vcpkg issue tracker. I think it is better if he continues there. The problem anyway is not related to darknet nor vcpkg, but just the very moltitude of opencv installations on his machine.

Yes, he get such error:
> CMake Error at C:/Program Files/CMake/share/cmake-3.14/Modules/CMakeDetermineSystem.cmake:99 (message):
>   Could not find toolchain file: /scripts/buildsystems/vcpkg.cmake
> Call Stack (most recent call first):
>   CMakeLists.txt:14 (project)
> 
> 
> Configuring incomplete, errors occurred!

**Pull request merged**
