### PR TITLE
Build clarification

### PR DESCRIPTION
**Pull request by acxz**
I went ahead and reorganized the readme with regards to installation, particularly `cmake` on linux.
Re: #3345 

(My text editor removes trailing whitespaces by default so sorry in advance for that.)

### CODE REVIEW

**Comment by cenit** [comment]
In markdown trailing white spaces are important. Please add an exception to the remove trailing white spaces for md files and rework your pr ;)

**Comment by acxz** [comment]
I actually don't think (99.99% sure) that trailing whitespaces change anything in markdown. You can take a look at the readme on my [fork](https://github.com/acxz/darknet/tree/build_clarification) and there is nothing different besides the content I changed.

**Comment by cenit** [comment]
By default, two spaces in markdown is the same as a <br> (newline). Maybe they were not important in those position in particular. My note was a general rule

**Comment by acxz** [comment]
I see, TIL thank you telling me. In any case I went through my changes using Github's README previewer (the one that shows diffs in the formatted markdown file) and all is good.

**Comment by acxz** [comment]
Closing this PR and opened #3375 without trailing whitespace clean up.

**Pull request closed without merging**
