### PR TITLE
move to opencv4.5 on vcpkg in ci, do not default to ninja on windows, update README

### PR DESCRIPTION
**Pull request by cenit**
fixes: #7273 
fixes: #7278

### CODE REVIEW

**Comment by cenit** [comment]
@AlexeyAB can we merge this one? Please let me know.
Unfortunately windows build is still broken with vcpkg but I cannot reproduce it locally. It will be interesting to find the culprit!

**Comment by cenit** [comment]
I have disabled cuda in the windows vcpkg build for now, to have a green badge. I will work towards fully restoring the check as soon as possible.
In the meantime, I am very positive about merging this PR if all checks are green

**Comment by AlexeyAB** [comment]
@cenit Hi,

>  I have disabled cuda in the windows vcpkg build for now, to have a green badge. I will work towards fully restoring the check as soon as possible.

Did you resotrre cuda in the windows vcpkg build?
Can we merge this PR?

**Comment by cenit** [comment]
no i was experimenting a little bit more. Today i will try to finish and i will tell you

**Comment by AlexeyAB** [comment]
@cenit Hi,

There seems to be compilation errors in CI:

* Travis-CI: `macOS - clang - vcpkg`

* Travis-CI: `ubuntu 18.04 - gcc - CUDA 10 - vcpkg`

----

* GitHub Actions: `ubuntu-makefile`
> /usr/local/cuda/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
>   138 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!

----

* GitHub Actions: `ubuntu-cuda`

>   -- Detecting CXX compile features
>   -- Detecting CXX compile features - done
>   -- Looking for a CUDA compiler
>   -- Looking for a CUDA compiler - NOTFOUND
>   CMake Error at CMakeLists.txt:92 (message):
>   Error:   CUDA not found, please build explicitly with -DENABLE_CUDA=OFF if you do
>     not want CUDA
>   
>   
>   -- Configuring incomplete, errors occurred!

----

* GitHub Actions: `win-vcpkg-cuda`

**Comment by cenit** [comment]
yes. Sorry too much work and this PR didn’t receive enough care from me. I’ll fix those problems asap so that we can merge it

**Comment by AlexeyAB** [comment]
@cenit Great, thanks!

**Comment by cenit** [comment]
hi @AlexeyAB, PR is ready :)

**Comment by AlexeyAB** [comment]
@cenit Great, Thank you so much! I merged PR.

**Comment by AlexeyAB** [comment]
@cenit 

* Why is it `.\build.ps1 -UseVCPKG -EnableOPENCV -EnableCUDA -EnableCUDNN` better than `.\vcpkg install darknet[opencv-base,cuda,cudnn]:x64-windows` ?

* Also about these commands, can we just put them to the single build.ps/cmd file, so the user just should run one file instead of these commands?
```PowerShell
PS Code/>              git clone https://github.com/microsoft/vcpkg
PS Code/>              cd vcpkg
PS Code/vcpkg>         ./bootstrap-vcpkg.sh
PS Code/vcpkg>         $env:VCPKG_ROOT=$PWD
PS Code/vcpkg>         cd ..
PS Code/>              git clone https://github.com/AlexeyAB/darknet
PS Code/>              cd darknet
PS Code/darknet>       ./build.ps1 -UseVCPKG -EnableOPENCV -EnableCUDA -EnableCUDNN
```

**Comment by masa126** [comment]
Hi @AlexeyAB 
Because of error happened at 112 in CMakeLists.txt, I can't build GPU version of yolo-v4 with Windows.
The new env CUDACXX is empty which might be caused by "check_language(CUDA)"

The power shells in the above also shows the following errors at the end.
 CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
 CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
Please let me know the way to build GPU version with CMake on Windows.
The old version of  CMakeLists.txt (downloaded in Aug.) with old CMake builds GPU version properly.

**Comment by cenit** [comment]
can you please post full log in a new issue?

**Comment by masa126** [comment]
@cenit  Hi,
Please find my report about CMake error for the legacy way to build yolo-v4
Sorry too long message.

I downloaded Darknet-V4 zip file on this May. 
After I uninstalled all CUDA named programs from Control Panel, I re-installed CUDA 10.0 on my Win 10 machine and invoke CMake 3.18.2.
CMake found CUDA compiler properly but failed to generate the VS 2015 project.
Its error log shows “'pthread.h':No such file or directory. 
As I don’t use VCPKG, I turned off VCPKG_BUILD_OPENCV_WITH_CUSA, then it succeeded to generate VS 2015 project. 
But I failed to build Darknet because of errors. 
I found CUDA 10.2 or 11.2 was required for darknet-v4, then I installed CUDA 11.2.
Now there are two CUDAs on my Win machine.
CUDA_PATH is set for CUDA 11.2 and CUDA_PATH_V11.2 is created automatically.
Of cause, CUDA 11.2 is specified at the top of Path.
Here I invoke CMake after deleting its Cash, then CMake fails to find CUDA compiler.
If there are multiple CUDA versions on a machine, the scripts of CMakeLists.txt might fail to find the CUDA compiler specified in CUDA_PATH.

So, I uninstall CUDA 10.2 programs from Control Panel and delete its folder in Program Files\NVIDIA GPU Computing Toolkit.
But CMake failed to find CUDA compiler. (You can find the error messages at the bottom as FYI.)
Now there is only CUDA 11.2 on my machine, but CMake fails to find CUDA compiler.

OK, here is the last try.
After I uninstalled all CUDA programs, I installed CUDA 11.2 again and invoke CMake.
Still CMake failed to find CUDA compiler.  It is very strange.
There might be bugs in CMakeLists.txt.
It can find CUDA 10.0 but fail to find CUDA 11.2.
The old CMakeLists.txt for CMake 13.8 or higher, which was in the zip file downloaded in the last Aug., can find CUDA compiler properly. 

** FYI
I have double-checked CMake results under CUDA 10.0 only condition.
The output from CMake with CUDA 10.0 succeeded to generate VS 2015 project is as follows:
vcpkg not found, toolchain not defined, using integrated libs on win32
Selecting Windows SDK version 10.0.14393.0 to target Windows 10.0.19042.
Selected CMAKE_CUDA_ARCHITECTURES: 30
Your setup does not support half precision (it requires CUDA_ARCHITECTURES >= 70)
PThreads_windows_DLL_DIR: D:/Deep_Learning/darknet-v4-21May/3rdparty/pthreads/include/../bin
OpenCV ARCH: x64
OpenCV RUNTIME: vc14
OpenCV STATIC: OFF
Found OpenCV 3.4.5 in C:/Programs/opencv345/build/x64/vc14/lib
You might need to add C:\Programs\opencv345\build\x64\vc14\bin to your PATH to be able to run your applications.
  ->  darknet is fine for now, but uselib_track has been disabled!
  ->  Please rebuild OpenCV from sources with CUDA support to enable it
CMAKE_CUDA_FLAGS:  -Wno-deprecated-declarations -Xcompiler="/wd4013,/wd4018,/wd4028,/wd4047,/wd4068,/wd4090,/wd4101,/wd4113,/wd4133,/wd4190,/wd4244,/wd4267,/wd4305,/wd4477,/wd4996,/wd4819,/fp:fast,/DGPU,/DCUDNN,/DOPENCV" -D_WINDOWS -Xcompiler=" /GR /EHsc"
Configuring done
Generating done

**There are 6 error messages from VS2015
1) identifier "cudaStreamCaptureModeGlobal" is undefined	darknet #706
2) too many arguments in function call 	network_kernels.cu in darknet #706
3) identifier "cudaStreamCaptureModeGlobal" is undefined	dark #706
4) too many arguments in function call 	network_kernels.cu in darkn #706
5) and 6)  MSB372  CUDA compile parameters definition #712

Regards,

**Comment by cenit** [comment]
please update darknet and then post full logs from 

.\build.ps1

**Comment by masa126** [comment]
I tried it but the configuration process was failed shown as below:

CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j9
    Working Directory: D:/Deep_Learning/darknet-v4-May15/vcpkg/buildtrees/zlib/x64-windows-dbg
    See logs for more information:
      D:\Deep_Learning\darknet-v4-May15\vcpkg\buildtrees\zlib\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:104 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/zlib/portfile.cmake:33 (vcpkg_install_cmake)
  scripts/ports.cmake:142 (include)

Error: Building package zlib:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x64-windows
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9

Additionally, attach any relevant sections from the log files above.
-- Running vcpkg install - failed
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:898 (message):
  vcpkg install failed.  See logs for more information:
  D:\Deep_Learning\darknet-v4-May15\build_release\vcpkg-manifest-install.log
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.20/Modules/CMakeDetermineSystem.cmake:123 (include)
  CMakeLists.txt:71 (project)
-- Configuring incomplete, errors occurred!

**Comment by cenit** [comment]
please open issues and do not write here in a merged PR about unrelated things

anyway, as the messages says, please show this log for more information:
D:\Deep_Learning\darknet-v4-May15\vcpkg\buildtrees\zlib\install-x64-windows-dbg-out.log

**Comment by masa126** [comment]
[install-x64-windows-dbg-out.log](https://github.com/AlexeyAB/darknet/files/6483699/install-x64-windows-dbg-out.log)
here is the log.

**Comment by cenit** [comment]
can you update your Visual Studio? it looks like your version has a bug which is fixed in newer versions

**Comment by masa126** [comment]
updated toVS2019 Com and installed CUDA 10.2.
still not work.
[config-x64-windows-out.log](https://github.com/AlexeyAB/darknet/files/6488514/config-x64-windows-out.log)

**Comment by cenit** [comment]
there is no error in the config file. maybe the error is in the install file (same as above)
but the config file tells you that it is still using the same old visual studio version…. can you please remove it?

**Comment by masa126** [comment]
Uninstalled VS2015 and download darknet-masterzip again.
Then invoke .\build.ps1 -UseVCPKG -EnableOPENCV -EnableCUDA –EnableCUDNN
Still not work.
[ps_build_error.txt](https://github.com/AlexeyAB/darknet/files/6489325/ps_build_error.txt)

**Comment by masa126** [comment]
Rr-install VS2019 Com. Eng. version and invoke .\build.ps1 ....
It started to build.
Thank you for your help.

**Comment by AlexeyAB** [comment]
> Uninstalled VS2015 and download darknet-masterzip again.
> Then invoke .\build.ps1 -UseVCPKG -EnableOPENCV -EnableCUDA –EnableCUDNN
> Still not work.
> [ps_build_error.txt](https://github.com/AlexeyAB/darknet/files/6489325/ps_build_error.txt)

@cenit Hi, Why does it require an English language package?

> -- Running vcpkg install
> Warning: The following VS instances are excluded because the English language pack is unavailable.
>     C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
>     C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
> Please install the English language pack.
> No suitable Visual Studio instances were found
> -- Running vcpkg install - failed

**Comment by cenit** [comment]
https://github.com/microsoft/vcpkg/issues/2295#issuecomment-349128392

vcpkg enforces English language as required. The same requirement is not needed if not using vcpkg.
It is necessary because *many, many* libraries fail without English installed, and so it became a requirement. I will add an explicit note in our setup part inside README.

**Comment by cenit** [comment]
> Rr-install VS2019 Com. Eng. version and invoke .\build.ps1 ....
> It started to build.
> Thank you for your help.

very good.
Yes English language is required. Sorry for missing that info, we will try to be more clear in the future

**Pull request merged**
