### PR TITLE
Log file and line

### PR DESCRIPTION
**Pull request by stephanecharette**
Modified memory alloc and error functions in utils to take a filename and a line number.  Then updated the calls to xcalloc() for example to pass in `__FILE__` and `__LINE__`.  This way we can record an actual file and line number, instead of the previous call to `assert(0)` which would always display the very generic `error()` location which wasn't useful.

In addition, converted several additional calloc() calls to xcalloc() so darknet can display the right error message and terminate instead of blindly attempting to write to a null pointer.

### CODE REVIEW

**Comment by cenit** [comment]
you are modifying this PR and also #6833 and both now are consistent with commits and modifications.
Do you want to rescope your PR to the two different topics? Is it necessary to make one dependent to the other? Do you prefer to close one and continue only in the other?

**Comment by stephanecharette** [comment]
> you are modifying this PR and also #6833 and both now are consistent with commits and modifications.

I didn't realize that old 1-line PR from 8 months ago hadn't been merged yet.

**Comment by AlexeyAB** [comment]
@stephanecharette Hi, Thanks!
Yes, I thought about this.

Is it better to use function + define?
```cpp
void *xcalloc_custom(size_t nmemb, size_t size, const char *filename, const int linenum) {
    void *ptr=calloc(nmemb,size);
    if(!ptr) {
        calloc_error(size, filename, linenum);
    }
    return ptr;
}

#define xcalloc(nmemb, size, filename, linenum) (xcalloc_custom(nmemb, size, filename, linenum))`
```

instead of replacing all `xcalloc()` calls?


----

In C++ I use my custom try-catch macros:
https://github.com/AlexeyAB/Port_Mapping/blob/master/src-boost-asio-portmapping/try_catch_to_cerr.hpp
and I use it in such a way to generate full **stacktrace** (with all previous calls):

```cpp
try_catch_to_cerr(THROW_PLACE, [&]() {
    func1();
    some code...
    func2();
    some code...
} );
```

**Comment by stephanecharette** [comment]
> Is it better to use function + macros?

There are many different ways we can do it.  One advantage of this way is it also made it very obvious where calls were still being made to calloc() instead of xcalloc().

Are you asking me to change it to a macro instead of passing in `__FILE__` and `__LINE__` everywhere?

**Comment by AlexeyAB** [comment]
@stephanecharette Yes, if there are no big problems with the macro here, then it might be better to replace it with a macro.

**Comment by cenit** [comment]
```
..\src\http_stream.cpp(49): error C3861: 'xcalloc': identifier not found
```

**Pull request closed without merging**
