### PR TITLE
use newer Ubuntu for CI, minor fixes for darknet library (export missing defines and includes, hide unnecessary public symbols)

### PR DESCRIPTION
**Pull request by cenit**

### CODE REVIEW

**Comment by cenit** [comment]
@AlexeyAB please let me know your opinion on this PR. I thought that upgrading ubuntu from 14.04 to 18.04 would be better to align with typical expectations from userbase.

I had to fix a bug in an mm256 instruction which was "malformed" and that errored on brand new clang on linux.
It was requesting the second parameter as a constant, not as a variable (even if const, it was not ok)
I found out that switching on it and writing it explicitly is the new best practice. Since the range of the index is from 0 to 7 the code didn't even become too cumbersome.

In the meantime I reduced the test matrix to something that is more manageable, but at the same time generic enough. It should resemble what you once told me, I hope.

For me, it's ready for merging (in case of green light, which i am almost sure will happen, since locally works fine)

**Comment by HagegeR** [comment]
I've looked at it, and although you've updated the build of ubuntu, you're still downloading the CUDA from the old branch, IDK if it's a problem really but surely updating it as well won't do no harm

https://github.com/AlexeyAB/darknet/blob/769f76ef6292b5aebf6299c4474c5105eb33bf90/.travis.yml#L161

https://github.com/AlexeyAB/darknet/blob/769f76ef6292b5aebf6299c4474c5105eb33bf90/.travis.yml#L178

https://github.com/AlexeyAB/darknet/blob/769f76ef6292b5aebf6299c4474c5105eb33bf90/.travis.yml#L192

**Comment by cenit** [comment]
You are right, it might be time to also use CUDA 10.1

**Comment by AlexeyAB** [comment]
@cenit Hi, Thanks! Yes, you can merge it.

**Comment by AlexeyAB** [comment]
@cenit Hi,

It seems there are some errors in the current Master branch, so can you solve it in your PR?

* `CMake Error at /usr/share/OpenCV/OpenCVModules.cmake:186 (message):` https://travis-ci.org/AlexeyAB/darknet/jobs/567032679#L1095

----

* https://travis-ci.org/AlexeyAB/darknet/jobs/567032644#L870
```
/home/travis/build/AlexeyAB/darknet/src/gemm.c:553:25: fatal error: argument to
871      '__builtin_ia32_vec_ext_v8si' must be a constant integer
872    return _castu32_f32(_mm256_extract_epi32(_mm256_castps_si256(a), index));
```

----

* https://travis-ci.org/AlexeyAB/darknet/jobs/567032665#L184
```
The following packages have unmet dependencies:
185 clang-6.0 : Depends: libjsoncpp0 (>= 0.6.0~rc2) but it is not installable
186E: Unable to correct problems, you have held broken packages.
apt-get.diagnostics
187apt-get install failed
326The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install libopencv-dev clang-6.0" failed and exited with 100 during .
```

**Comment by cenit** [comment]
All of them are already solved by this pr.
If you have time to check it, that would be awesome. Otherwise, for me it’s ready for merging

**Comment by cenit** [comment]
just give me a couple of minutes to merge your last work

**Comment by AlexeyAB** [comment]
@cenit Ok

**Comment by cenit** [comment]
Ok now this branch contains your last work. It should build fine and without problems recently appeared on travis

**Comment by AlexeyAB** [comment]
@cenit Hi,

Please, can you say, why we get a compilation error for `macOS - clang - vcpkg` on TravisCI?

image

**Comment by cenit** [comment]
It’s due to ninja 1.10, which has been distributed broken by ninja devs themselves and unfortunately accepted as that by vcpkg. Here it is an issue open to track progress. In the meantime, do you prefer to disable that build?
https://github.com/microsoft/vcpkg/issues/10890

**Comment by AlexeyAB** [comment]
@cenit Thanks!

Does this bug also prevent Darknet compilation using vcpkg / build.ps/sh with Clang or macOS?

> In the meantime, do you prefer to disable that build?

No, let it remain, at least I will know when the compilation will work using the vcpkg.

**Comment by cenit** [comment]
vcpkg is broken on macOS as of now, due to this problem, if your OS is not Catalina (10.15, the latest one). Usually people have systems up to date, but still some people might have problems.
Ninja 1.10.1 will contain necessary fix, but it is still unreleased. As soon as it will be released, and vcpkg accepts it, problems should disappear also for people not using “latest and greatest” macOS

**Comment by cenit** [comment]
If you are on Catalina, everything works as it should. If you are using macOS 10.12/10.13 (like travis CI is), then ninja is broken...

**Pull request merged**
