### PR TITLE
enable random resize training for efficient net

### PR DESCRIPTION
**Pull request by dccho**
fix bugs to enable random resize training for efficientnet including squeeze&excitation and dropout.

### CODE REVIEW

**Comment by AlexeyAB** [comment]
@dccho Thanks! Did you successfully train and test it on EfficientNet and/or MixNet? https://github.com/AlexeyAB/darknet/issues/4203#issuecomment-553129025

**Comment by dccho** [comment]
@AlexeyAB I'm training my own network which is similar to efficientnet without any error so far. Due to lack of resource, I haven't tested original EfficientNet and MixNet on ImageNet dataset.

**Comment by AlexeyAB** [comment]
@dccho Do you get good Top1/5 accuracy on your dataset with your network?

**Comment by dccho** [comment]
@AlexeyAB I will share the mAP of my detection network maybe tomorrow. It is just beginning of training now.

**Comment by AlexeyAB** [comment]
@dccho So did you test it successfully?

**Comment by dccho** [comment]
@AlexeyAB I tested random resize training in my own network and dataset, but I cannot get better result. It is because my own network is quite small and it cannot cover varieties of input size. I tried to train original enet-coco with random resize on COCO dataset but it was expected to take couple of weeks to finish training because I only have one gpu in my computer.

**Comment by AlexeyAB** [comment]
@dccho Ok, I will merge it, since obviously it works without errors.

**Pull request merged**
