### PR TITLE
[CI] add scripts for travis and appveyor

### PR DESCRIPTION
**Pull request by cenit**
as per title, here I propose adding recipes for CI with many configurations tested. We can discuss even more of them if necessary, or remove some / add to allowed_failures if considered unnecessary (or broken and unfixable)

### CODE REVIEW

**Comment by AlexeyAB** [comment]
@cenit Thanks!

* It would be nice to add compiling with CUDA too. May be we can use something like this: https://github.com/BVLC/caffe/blob/master/scripts/travis/install-deps.sh#L81-L111 or if there are any better suggestions.
    CUDA and cuDNN can be downloaded from:
    http://developer.download.nvidia.com/compute/machine-learning/repos/
    http://developer.download.nvidia.com/compute/cuda/repos/
    For example, there are the latest versions of for Linux Ubuntu 18.04 x86_64:
    * CUDA 10.0     `cuda-repo-ubuntu1804_10.0.130-1_amd64.deb` http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/

    * cuDNN 7.5 `libcudnn7_7.5.0.56-1+cuda10.0_amd64.deb`  http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/



* I still can't compile it without this line on Linux https://github.com/AlexeyAB/darknet/pull/2476/files#diff-af3b638bc2a3e6c650974192a53c7291L116

* Also why did you comment these lines: https://github.com/AlexeyAB/darknet/pull/2476/files#diff-180360612c6b8c4ed830919bbb4dd459R13

* Did you test it on local PC and/or on remote Server?
    It looks like compilation aren't passed on remote server
    * Windows https://ci.appveyor.com/project/cenit/darknet/builds/22629402
    * Linux https://travis-ci.com/cenit/darknet/jobs/180298388

**Comment by cenit** [comment]
The PR is in draft because it is not ready to merge. For sure there are some small mistakes that need corrections.
I have never used CUDA on travis/appveyor, I will try to follow caffe recipe and learn something in the meantime.
For what concern the additional include, I think it is more harmful than useful. I have not been able to build darknet anymore correctly since that rushed line... I'd prefer to avoid it until we better understand what's going on on your computer and better understand how to reproduce your setup

**Comment by AlexeyAB** [comment]
> For what concern the additional include, I think it is more harmful than useful. I have not been able to build darknet anymore correctly since that rushed line... I'd prefer to avoid it until we better understand what's going on on your computer and better understand how to reproduce your setup

Ok.

**Comment by cenit** [comment]
i fixed some bugs in the ci scripts and made them more resilient to download errors. I opened it to merge but I will try to add CUDA CI tests as soon as possible anyway. Please let me know any other comment you may have

**Comment by AlexeyAB** [comment]
@cenit Thanks, great job!
It looks like all the tests passed. If the PR is ready - I can Merge it.

**Comment by cenit** [comment]
unfortunately I have to debug the cuda tests more: if you look carefully, CUDA is not found and therefore not used...

**Comment by cenit** [comment]
I forgot to export the CUDACXX variable, let me try this new round of CI tests to see if now cuda is seen

**Comment by cenit** [comment]
ok it's done :)
If it's ok for you @AlexeyAB, it's ready to merge
CUDA builds are tested only on linux
Unfortunately it seems impossible to install CUDA on Windows or on macOS without installing nvidia drivers, which require nvidia card.

I had to comment out two unused functions in a .cu file because Clang was complaining, due to openmp usage by nvcc (probably nvcc was defaulting to gcc even if clang was used and so enabling the unsupported omp...). I have some ideas about the problem, which was very strange (using -ccbin to nvcc to force the correct compiler), but since the two functions are not used at all, the best solution was just to remove them. I'd also move them away from a cu file, btw, as a cleaner solution...

**Comment by AlexeyAB** [comment]
@cenit Thanks!

* When OpenCV compiled without CUDA, a compilation error of the `uselib_track` project is generated. It confuses people, **they think that everything was compiled incorrectly**. Can we not compile the `uselib_track` project if there is an OpenCV without CUDA. Or if we can't check wether OpenCV compiled with CUDA, then can we at least set `uselib_track` compilation disabled by default (we will should manually enable it, as we done it for ENABLE_CUDA). https://github.com/AlexeyAB/darknet/issues/2472#issuecomment-467707382

----

> Unfortunately it seems impossible to install **CUDA on Windows** or on macOS without installing nvidia drivers, which require nvidia card.

* Did you try to use such CUDA installation? https://github.com/ethereum-mining/ethminer/blob/master/appveyor.yml
    It looks like CUDA can be used with Appveyor on Windows: https://ci.appveyor.com/project/ethereum-mining/ethminer/builds/22661574/job/m46v86wojxdi6jmj#L326

----


> I had to comment out two unused functions in a .cu file because Clang was complaining, due to openmp usage by nvcc

Yes, I will should at least move not-CUDA functions from cu-files to c-files, or delete them.

**Comment by cenit** [comment]
I tried to implement CUDA builds on Windows, let's see the output.
I also added a parameter to skip building uselib_track if the OpenCV version found does not have CUDA support. Thanks for noticing, it was a combination that I didn't even tested.

**Comment by cenit** [comment]
@AlexeyAB running nvcc.exe plain and simple on windows works even without installation. That's how they use it in ethereum-mining. Unfortunately for us we also depend on other CUDA libs, which without a proper installation do not work easily. I tried another test on appveyor, unfortunately I cannot/don't want to mess my setup trying to reproduce locally the situation, so it's not easy to try to fix.
I hope it works now, but if it does not work, I'd like to merge the PR as it is now, just let me know if you prefer to keep the Windows CUDA build inside the allowed failures or removed (again, in the not-so-impossible case that it still does not work).

**Comment by cenit** [comment]
CUDA website is down, CI is impossible to test for now. I cancelled the build, will try again later
https://developer.nvidia.com/compute/cuda/10.0/Prod/local_installers/cuda_10.0.130_411.31_windows is not working...

**Comment by AlexeyAB** [comment]
@cenit Thanks!

If this is difficult to do now, then you can disable the CUDA compilation check in Appveyor. And I will merge this PR.

Yes, it didn't work. 
Now it seems work again:
* https://developer.nvidia.com/compute/cuda/10.0/Prod/local_installers/cuda_10.0.130_411.31_windows
* https://developer.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda_10.1.105_418.96_windows.exe



----

As I understand we should do the following commands: https://www.olegtarasov.me/build-cuda-projects-with-appveyor/

```
@echo off
echo Downloading CUDA toolkit 10
curl -L https://developer.nvidia.com/compute/cuda/10.0/Prod/local_installers/cuda_10.0.130_411.31_windows -o cuda_10.0.130_411.31_windows.exe
7z x cuda_10.0.130_411.31_windows.exe -ocuda
cd cuda
echo Installing CUDA toolkit 10
setup.exe -s compiler_10.0 ^
                           cublas_10.0 ^
                           cublas_dev_10.0 ^
                           cudart_10.0 ^
                           curand_10.0 ^
                           curand_dev_10.0 ^
                           visual_studio_integration_10.0

if NOT EXIST "%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin\cudart64_100.dll" ( 
echo "Failed to install CUDA"
exit /B 1
)

cd ..

set PATH=%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin;%PATH%
set CUDA_PATH=%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v10.0
set CUDA_PATH_V9_0=%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v10.0

nvcc -V

cd "%APPVEYOR_BUILD_FOLDER%"
```

**Comment by cenit** [comment]
Hi @AlexeyAB 
appveyor is running now, with opencv[cuda] disabled but darknet CUDA build enabled anyway. Let's see if it works then you can merge.
I did the installation of CUDA in a different way, more manual:
```
curl -L https://developer.nvidia.com/compute/cuda/10.0/Prod/local_installers/cuda_10.0.130_411.31_windows -o cuda_10.0.130_411.31_windows.exe
mkdir C:\CUDATEMP
mkdir C:\CUDA
7z x cuda_10.0.130_411.31_windows.exe -oC:\CUDATEMP
cd C:\CUDATEMP
FOR /D %%G in ("*") DO xcopy C:\CUDATEMP\%%G\* C:\CUDA\ /s /y
```
the snippet that you found is much cleaner! Let's keep it for a v2 revision, I will use it for sure after testing! I tried with the silent installation (-s) but got some errors related to automatic checks of installed drivers and so I did everything manually, but maybe I did something wrong...

**Comment by AlexeyAB** [comment]
@cenit 

Ok, after that Appveyor and Travis tests will be passed, I will merge this PR.
So all other improvements can be added in the further PRs: opencv[cuda], cudnn, one-click-installation...

**Comment by AlexeyAB** [comment]
@cenit I merged it, thanks for PR!

**Comment by cenit** [comment]
@AlexeyAB thanks.
I tried in a small test repository the clean "setup.exe" silent install of cuda but it fails:
https://ci.appveyor.com/project/cenit/cuda-ci-tests/builds/22749448
I will investigate it better for the future

**Comment by AlexeyAB** [comment]
@cenit 

Build for `MacOS gcc@5 opencv@3` is failed in Travis CI: https://travis-ci.org/AlexeyAB/darknet/jobs/500411304#L3483

It was solved in this way in the Caffe - it is required to use `-lopencv_imgcodecs` for OpenCV 3.0: https://github.com/BVLC/caffe/pull/3186/files
So may be we can solve it in the same way.

**Pull request merged**
