### PR TITLE
improve compatibility with c++ compilers

### PR DESCRIPTION
**Pull request by cenit**
In order to try building darknet with vcpkg and newer OpenCV libs, I improved code compatibility with c++ compilers and added a CMakeLists.txt (required by vcpkg, can remove from here if really unwanted).

### CODE REVIEW

**Comment by cenit** [comment]
I saw the results from CircleCI. I will fix the errors ASAP, it looks like I made some modifications which implied the presence of OpenCV without guard clauses. In the meantime please let me know if this PR could be of any interest to your wonderful project. For me it would be a great way to avoid maintaining a big patch set on top of your repo. I hope some interesting points can be found here anyway, for example the easy configuration and automatic switch between the manual flags from your makefile depending on the computer setup

**Comment by AlexeyAB** [comment]
@cenit Hi,
Thanks for your PR!

This PR can be interesting if we divide it into several PRs:

1. `CMakeLists.txt +  cmake/Modules/` - it would be greate, if it can find automatically all `*.c`, `*.h` files  (and `*.cu` if GPU enabled) in the `/src/` directory , so we can add new `c/h`-files there without any changes in `CMakeLists.txt +  cmake/Modules/`. 
    So only `include/darknet.h` and `src/http_stream.cpp` should be specified in `CMakeLists.txt` instead of full list https://github.com/AlexeyAB/darknet/pull/2394/files#diff-af3b638bc2a3e6c650974192a53c7291R146

2. Only such fixes - which removes some warnings and fix obvious issues:
   * https://github.com/AlexeyAB/darknet/pull/2394/files#diff-a8f97d0ae44b45db073c59776b9d413fR14
   * https://github.com/AlexeyAB/darknet/pull/2394/files#diff-caba6cc2705c7ccdac0742dca992fc0cR8
   * https://github.com/AlexeyAB/darknet/pull/2394/files#diff-6a9bf0605a53a6f302e1b757e52a179fR16
   * https://github.com/AlexeyAB/darknet/pull/2394/files#diff-abb9d4d4e8b0007dd1d597c2c2c2bea6R288
   * https://github.com/AlexeyAB/darknet/pull/2394/files#diff-b8584d8d937b42da045ff7de595f044bR12

3. Any other fixes: non-obvious changes, explicit casting or things where we need to look - is it really necessary, and does it break something

----

Also why do you use explicit casting in C files, while it is compiled by using C-compiler (not C++)? https://github.com/AlexeyAB/darknet/pull/2394/files#diff-fd5d3ca423ea8b7ee7603f7341b278e7R35

If we want to solve an issue with supporting OpenCV >= 3.4.0 which doesn't support C API anymore, then I will try to add `image_opencv.cpp` with C++ -> C wrapper between OpenCV (C++) and Darknet (C). 
It would be better to add try-catch for every OpenCV C++ function, than using OpenCV C API. Because even C-functions in OpenCV can throw exceptions.

**Comment by cenit** [comment]
Hi Alexey,
thanks for the quick reply

1. Looking automatically for all `.c` or `.h` files would be very easy, but it is considered a non-best practice in the CMake world. Since you prefer the automatic selection, I will do it soon (usually people prefer to fully control what is going to be compiled and what not)

1b. `cmake/Modules` are working and tested to fully remove (in perspective, not now of course) your `3rd-party` folder. Just installing with `vcpkg` OpenCV, pthreads, ffmpeg (and automatically their relative dependencies) is enough to fully build darknet

2. Ok

3. In reality using my proposed toolchain your sources are built using a C++ compiler, not a C compiler, and so explicit casts everywhere are necessary. They should not break anything, btw. Do you see any regression here?
Having touched all of them I saw also some wrong allocations (luckily always bigger than necessary, so no big problem). I had to build sources using a C++ compiler because recently, on Windows, `OpenCV` versions newer than 3.4.1 started including C++ headers inside C headers without any guard clauses. They do not even want to fix it, because of the extremely deprecated C API (whatever, I think this is a bad attitude from their side). If not built using C++ compiler you receive warnings about the std:: namespace included... The moment you will split OpenCV from darknet completely, then we can reverse the line `set_source_files_properties(${sources} PROPERTIES LANGUAGE CXX)` and restore automatic language detection in CMake.

Today I am really busy at work, I will try to do the work we are discussing as soon as possible, in the weekend if really late

**Comment by cenit** [comment]
I think I will drop the 9581fb5 commit ` [add CMake support](/AlexeyAB/darknet/pull/2394/commits/9581fb5bf5005e02d1942f635152dfb0c7de7eff)` from this PR and I will open a different one for it, since it is completely detachable from the rest of this PR

**Comment by AlexeyAB** [comment]
@cenit Hi,

> `cmake/Modules` are working and tested to fully remove (in perspective, not now of course) your `3rd-party` folder. Just installing with `vcpkg` OpenCV, pthreads, ffmpeg (and automatically their relative dependencies) is enough to fully build darknet

This is cool! Just we have to make sure that it does not conflict with already installed libraries.

> I think I will drop the [9581fb5](https://github.com/AlexeyAB/darknet/commit/9581fb5bf5005e02d1942f635152dfb0c7de7eff) commit ` [add CMake support](/AlexeyAB/darknet/pull/2394/commits/9581fb5bf5005e02d1942f635152dfb0c7de7eff)` from this PR and I will open a different one for it, since it is completely detachable from the rest of this PR

It would be great.

**Comment by cenit** [comment]
I fixed some errors and removed the CMakeFiles.txt which is now in a different PR.
This PR (and the other one) by design should not be influent in any way to your usual toolchain, apart from some necessary fixes here and there. Please let me know any suggestion you may have or any necessary change you require for acceptance.

**Comment by AlexeyAB** [comment]
@cenit Thanks!

1. May be we should use `#include "getopt.h"` instead of `#include <getopt.h>` since in this case `getopt.h` is a local header-file?
* https://github.com/AlexeyAB/darknet/pull/2394/files#diff-42db8537ee80f3c37a01456b63f36daeR12
* https://github.com/AlexeyAB/darknet/pull/2394/files#diff-42db8537ee80f3c37a01456b63f36daeR12
* https://github.com/AlexeyAB/darknet/pull/2394/files#diff-81aff2576d313a7d43a9394480117921R2

2. And it looks like that `M_PI` is GNU definition, it isn't defined for MSVS
* https://github.com/AlexeyAB/darknet/pull/2394/files#diff-d63433b66e54cd65ded01be20041119cR1593
* https://github.com/AlexeyAB/darknet/pull/2394/files#diff-74710e3ecbe94109f39de34133e1c8caR717

3. Also I think we shouldn't brake old compilation ways for C-compiler. It breaks the C-compilation on Windows:
* https://github.com/AlexeyAB/darknet/pull/2394/files#diff-64a72cf3c7a2c448ff495afaa965179aR13
* https://github.com/AlexeyAB/darknet/pull/2394/files#diff-74710e3ecbe94109f39de34133e1c8caL17

4. What is the advantage of moving this section of code to the `darknet.h` API file? Since it is used only for sending MJPEG-stream or JSON-stream during detection on video (or only MJPEG-stream during training).
https://github.com/AlexeyAB/darknet/pull/2394/files#diff-06d7eaa529ff0d43e382b4b216f391c0R29

I think we should leave these definitions in the related c/h-files instead of moving it to the API:
* may just be at the top of the C file, so it can be easily found
* and it will not confuse users of API
```cpp
#define PORT unsigned long
#define ADDRPOINTER int*
#else
#define PORT unsigned short
#define SOCKET int
#define HOSTENT struct hostent
#define SOCKADDR struct sockaddr
#define SOCKADDR_IN struct sockaddr_in
#define ADDRPOINTER unsigned int*
#define INVALID_SOCKET -1
#define SOCKET_ERROR -1
#endif
#define FULL_MASK 0xffffffff
#define WARP_SIZE 32
#define BLOCK 512
#define NUMCHARS 37
#define NFRAMES 3
#define BLOCK_TRANSPOSE32 256
#define DOABS 1
#define SECRET_NUM -1234
#define C_SHARP_MAX_OBJECTS 1000
#define TILE_M 4 // 4 ops
#define TILE_N 16 // AVX2 = 2 ops * 8 floats
#define TILE_K 16 // loop
#ifndef __COMPAR_FN_T
#define __COMPAR_FN_T
typedef int (*__compar_fn_t)(const void*, const void*);
#ifdef __USE_GNU
typedef __compar_fn_t comparison_fn_t;
#endif
#endif
```

**Comment by cenit** [comment]
Thanks for your quick and meaningful feedback. I will try to improve the PR during the weekend following your requests :)

**Comment by cenit** [comment]
1. Yes you're perfectly right! Better to use the " around getopt.h!
2. No it is available also under MSVC, that's why I have this line in CMakeLists.txt: `add_definitions(-D_USE_MATH_DEFINES)`. If you do not want to add it to your custom solutions I can add this define in the sources to fix your build problems.
3. Yes, you're right also on this point! Sorry I didn't test the C building on Windows so I didn't notice these regressions
4. Left as a TODO for tomorrow

**Comment by cenit** [comment]
4. i tried my best to move many defs away from API file.

Please let me know if you need any other modifications before considering merge.

**Comment by AlexeyAB** [comment]
@cenit Hi,

> 2\. No it is available also under MSVC, that's why I have this line in CMakeLists.txt: `add_definitions(-D_USE_MATH_DEFINES)`. If you do not want to add it to your custom solutions I can add this define in the sources to fix your build problems.

Yes, I think we should add `#define _USE_MATH_DEFINES` in the code `utils.h` before `#include <math.h>`

----

> 1. i tried my best to move many defs away from API file.
> 
> Please let me know if you need any other modifications before considering merge.


Also it would be better if you remove `#include "darknet.h"` from `yolo_v2_class.hpp` and add it to the `yolo_v2_class.cpp`. So in the C++-API there will no C-API dependecies.
And these defenitions for API we can leave in both darknet.h and yolo_v2_class.hpp: https://github.com/AlexeyAB/darknet/pull/2394/files#diff-1351771290f9e0c55c0b52acfa26b981L2

**Comment by cenit** [comment]
I should have implemented requested changes, as always please let me know any remarks you may have

**Comment by cenit** [comment]
I will very soon also implement something along the lines of https://github.com/pjreddie/darknet/pull/1348 because I need it also for your version, since on `vcpkg` the default `OpenCV` will soon be 4.0. Please let me know if you prefer inside this PR or in another one that will follow afterwards

**Comment by AlexeyAB** [comment]
@cenit Thanks!

A few question:

* what is the reason to add `int skip` here? https://github.com/AlexeyAB/darknet/pull/2394/files#diff-96fe804ef0d90fb4d0adbde1a06d9393R194

* why did you add LIB_API for these internal functions? 
    * https://github.com/AlexeyAB/darknet/pull/2394/files#diff-f11e6de8641aab8d242e86cf21c7b672R62
    * https://github.com/AlexeyAB/darknet/pull/2394/files#diff-9041f67475c72da62bfaa47bc0d0f773R12


* and for these funcitons:
    * https://github.com/AlexeyAB/darknet/pull/2394/files#diff-f4e8b836b50d6649661063849b9dad0eR4
    * https://github.com/AlexeyAB/darknet/pull/2394/files#diff-dbbbab3f902e5aea9dfa2a3a98712ff9R32
    * https://github.com/AlexeyAB/darknet/pull/2394/files#diff-4c6cfd653d901467395b8d1169b3f2beR96

**Comment by AlexeyAB** [comment]
> I will very soon also implement something along the lines of [pjreddie#1348](https://github.com/pjreddie/darknet/pull/1348) because I need it also for your version, since on `vcpkg` the default `OpenCV` will soon be 4.0. Please let me know if you prefer inside this PR or in another one that will follow afterwards

Do you want to add image_opencv.cpp that will use C++ API of OpenCV and remove C API?
I think it would be better to use another PR.

**Comment by AlexeyAB** [comment]
@cenit 

Also, if we will use C++ API of OpenCV in a separate file `image_opencv.cpp` as here https://github.com/pjreddie/darknet/pull/1348 and will remove all C OpenCV API from every C-file, then is it really necessary to add C ++ compatibility in all of C-files offered by this PR?

**Comment by cenit** [comment]
- I had to add `int skip` because in the layer struct the function pointer has this interface: `(struct layer, int, float, float, float)` and `update_deconvolutional_layer` did't have that member.
- It became unnecessary after some work. Thanks for noticing, I removed them
- As before, removed
- I don't want to remove any C API. I just wanted to add with the minimum "noise" the possibility to build `darknet` also if OpenCV4 was found on the system. I think the changes should be kept to a minimum and I agree that in any case we can look for this change afterwards.

**Comment by AlexeyAB** [comment]
Thanks for PR!

Yes, I can build it with `opencv-3.4.5-vc14_vc15.exe`

But I can't build it with `opencv-4.0.1-vc14_vc15.exe` 

Even if I change
`#include <opencv2/imgcodecs/imgcodecs_c.h>`
to
`#include <opencv2/imgcodecs/legacy/constants_c.h>`

I get an error:
`D:\Darknet2\darknet_cpp_2\darknet\src\data.c(762): error C3861: cvLoadImage: identifier not found`

So it seems it is necessary to use `image_opencv.cpp` with OpenCV C++ API.

**Pull request merged**
