### PR TITLE
improve build process even more

### PR DESCRIPTION
**Pull request by cenit**
@AlexeyAB is this what you meant in https://github.com/AlexeyAB/darknet/pull/7279#issuecomment-820788011 ?

### CODE REVIEW

**Comment by cenit** [comment]
about `build.ps1` vs `vcpkg`, `build.ps1` uses `vcpkg` behind the scenes if requested, otherwise not.
It's just a generic script here that is transverse to all operating systems and all library mechanism: it's working with libraries provided by the user, the OS or vcpkg: you can/should always use `build.ps1` to build `darknet`

**Comment by cenit** [comment]
on the other hand, `script/setup.ps1` is a different beast, because it tries also to install missing applications (and as such is much more invasive on the user computer): git, cmake, cuda, visual studio, ninja, etc, upon which `build.ps1` is ... built (and errors out if missing without any possible other alternative)

**Comment by cenit** [comment]
@AlexeyAB if the CI has green light, for me you can already merge this PR

**Comment by AlexeyAB** [comment]
@cenit Thanks!

So now we can just run these commands and it will install: OpenCV, CUDA-runtime, cuDNN, ffmpeg and Darknet automatically?
```
PS Code/>              git clone https://github.com/AlexeyAB/darknet
PS Code/>              cd darknet
PS Code/darknet>       .\build.ps1 -UseVCPKG -EnableOPENCV -EnableCUDA -EnableCUDNN
```

**Comment by cenit** [comment]
opencv, stb, pthreads, cudnn yes,  `build.ps1` installs them through vcpkg

cuda, visual studio, cmake, git on the other hand should be already installed, or you can run `scripts/setup.ps1` (but this has to be run with administrative privileges)

**Comment by cenit** [comment]
do you think we can merge this pr or do you have any other question about it?

**Comment by AlexeyAB** [comment]
@cenit 

> opencv, stb, pthreads, cudnn yes, build.ps1 installs them through vcpkg

1. Will it install vcpkg automatically too?

> .\build.ps1 -UseVCPKG -EnableOPENCV -EnableCUDA -EnableCUDNN

2. What and how will be installed without flag `-UseVCPKG` ?

3. Can we change the default behavior?
* So if we want to install Darknet with VCPKG, OpenCV, CUDA, cuDNN, then just run `\build.ps1`
* if we want to install Darknet without them then run `.\build.ps1 -DisableVCPKG -DisableOPENCV -DisableCUDA -DisableCUDNN`

**Comment by cenit** [comment]
> 
> 1. Will it install vcpkg automatically too?
> 

yes, `build.ps1` tries to find `vcpkg` in some default locations but if not found it will be downloaded automatically

> 
> 2. What and how will be installed without flag `-UseVCPKG` ?
> 

without the `-UseVCPKG` flag, `build.ps1` does not install anything and relies on cmake finding libraries already installed on the computer.

> 
> 
> 3. Can we change the default behavior?
> 

`-EnableXxx` turn on options, while to disable you just omit the option. There is no "disable" flag, you just do not enable it.

The default behavior and the list of the switches are written at the very beginning of the `build.ps1` script

**Comment by cenit** [comment]
so for example, 

`.\build.ps1 -UseVCPKG -EnableOPENCV` uses vcpkg to install opencv (without cuda extensions, so uselib_track won't be built)

`.\build.ps1 -EnableOPENCV` looks for opencv already installed by the user on the computer. if opencv won't be found, it will error

**Comment by AlexeyAB** [comment]
I mean, can user just download https://github.com/AlexeyAB/darknet/archive/refs/heads/master.zip unpack it and run `.\build.ps1` by double-click or rigth-click -> Run with PowerShell (without flags `-UseVCPKG -EnableCUDA ...`), and will it install Darknet with OpenCV + CUDA + cuDNN support? Since this configuration is used for most cases.

If not, can we change `.\build.ps1` for this behavior?

**Comment by cenit** [comment]
Since flags in a powershell script are false by default and become true if written, I have to invert the logic and change all "-EnableXxx" in "-DisableXxx", so that if you do not write the flag, it is considered enabled by default

**Comment by cenit** [comment]
in any case at the moment the biggest number of install I think come from vcpkg directly.
In those case users just have to write

./vcpkg install darknet[full] 

and darknet will be installed with the build script called with all the flags :)

**Comment by AlexeyAB** [comment]
Ok, lets keep it as is. Thanks!

>in any case at the moment the biggest number of install I think come from vcpkg directly.
> In those case users just have to write
> ./vcpkg install darknet[full]

Should we add this command to the Readme.md as alternative way too?
Is there any statistic, how many times Darknet was downloaded by using ` ./vcpkg install darknet` ?
And how often `vcpkg` update Darknet, once per vcpkg-version / per-month, ...?

**Comment by cenit** [comment]
vcpkg updates darknet every time i have time to work on it.
that's why i would decouple it from your readme. I just had two extremely busy months and as you saw i wasn't able to keep up with the work here. if you redirect your most loyal users to an older version it might not be the best option

**Comment by AlexeyAB** [comment]
I just saw a lot of questions in Issues regarding a failed installation. And I do not know what exactly is the reason, or the compilation of the Darknet in VCPKG is broken, or bug is in 3rd party libs OpenCV/CUDNN/MSVS/..., or it is difficult for users to follow the required instructions. There seem to be some users who would prefer an easy install of the latest stable release over the most recent current commit.

Or can we just release **compiled binary files darknet.exe with all dependecies (CUDA, cuDNN, OpenCV, ...)**, can we do this or are there any licensing or other restrictions here? Can we get it directly from artifacts from GitHub-Actions / Travis-CI, especially for Windows?

**Comment by cenit** [comment]
installing a program from sources is always difficult. That's why a good CI system that checks many different configs is very useful.
At the same time, we have many different build methods here and it's difficult to maintain all of them. Here we have VS solutions, makefile and CMake.
I would push for a removal of the VS solution so that we do not have to maintain them anymore, and in the future also the makefile, keeping only CMake.
CMake is well tested in CI here and is also the only method tested by Microsoft in vcpkg in many different configurations.

For our support, every time I do a PR I try to add some useful informations about user configuration, in order to understand what's going on. At the moment the `build.ps1` script gives many info, starting from the very first line of output, to understand user config and what might be broken.

about vcpkg: at the moment darknet there still suffers about the VS 16.9 bug. I need this PR merged to finish the work there (gemm.c has some problems in ARM architectures and only this PR fixes them)

**Comment by cenit** [comment]
i can try an interactive mode. let me just do a quick experiment and i will let you know

**Comment by cenit** [comment]
@AlexeyAB ok now build.ps1 will ask user some basic questions if no flags are passed and if not opt-out of it.
Please let me know if it's better for you
I am waiting for this PR before being able to push a new darknet release on vcpkg

**Comment by AlexeyAB** [comment]
@cenit Thanks! Can I merge this PR now?

**Comment by cenit** [comment]
yes

**Comment by cenit** [comment]
please also do a "Squash and merge" in the button down here so that the commit history is cleaned up :)

**Comment by cenit** [comment]
i added a small commit which is failing. please let me check it

**Comment by AlexeyAB** [comment]
I merded this PR, thanks!

**Comment by AlexeyAB** [comment]
@cenit Hi,
Has this issue https://github.com/AlexeyAB/darknet/issues/7599#issuecomment-818909911 been resolved by the latest PRs? So now we may not un-install and then install MSVS/CUDA/Cmake/Ninja/... manually?

**Pull request merged**
